package com.artqiyi.tanqiu.job.domain;

import java.util.Date;

public class ScheduleJobFailLog {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column schedule_job_fail_log.id
     *
     * @mbg.generated Fri May 18 14:47:03 CST 2018
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column schedule_job_fail_log.job_id
     *
     * @mbg.generated Fri May 18 14:47:03 CST 2018
     */
    private Long jobId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column schedule_job_fail_log.job_name
     *
     * @mbg.generated Fri May 18 14:47:03 CST 2018
     */
    private String jobName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column schedule_job_fail_log.job_group
     *
     * @mbg.generated Fri May 18 14:47:03 CST 2018
     */
    private String jobGroup;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column schedule_job_fail_log.create_time
     *
     * @mbg.generated Fri May 18 14:47:03 CST 2018
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column schedule_job_fail_log.reason
     *
     * @mbg.generated Fri May 18 14:47:03 CST 2018
     */
    private String reason;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column schedule_job_fail_log.id
     *
     * @return the value of schedule_job_fail_log.id
     *
     * @mbg.generated Fri May 18 14:47:03 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column schedule_job_fail_log.id
     *
     * @param id the value for schedule_job_fail_log.id
     *
     * @mbg.generated Fri May 18 14:47:03 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column schedule_job_fail_log.job_id
     *
     * @return the value of schedule_job_fail_log.job_id
     *
     * @mbg.generated Fri May 18 14:47:03 CST 2018
     */
    public Long getJobId() {
        return jobId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column schedule_job_fail_log.job_id
     *
     * @param jobId the value for schedule_job_fail_log.job_id
     *
     * @mbg.generated Fri May 18 14:47:03 CST 2018
     */
    public void setJobId(Long jobId) {
        this.jobId = jobId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column schedule_job_fail_log.job_name
     *
     * @return the value of schedule_job_fail_log.job_name
     *
     * @mbg.generated Fri May 18 14:47:03 CST 2018
     */
    public String getJobName() {
        return jobName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column schedule_job_fail_log.job_name
     *
     * @param jobName the value for schedule_job_fail_log.job_name
     *
     * @mbg.generated Fri May 18 14:47:03 CST 2018
     */
    public void setJobName(String jobName) {
        this.jobName = jobName == null ? null : jobName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column schedule_job_fail_log.job_group
     *
     * @return the value of schedule_job_fail_log.job_group
     *
     * @mbg.generated Fri May 18 14:47:03 CST 2018
     */
    public String getJobGroup() {
        return jobGroup;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column schedule_job_fail_log.job_group
     *
     * @param jobGroup the value for schedule_job_fail_log.job_group
     *
     * @mbg.generated Fri May 18 14:47:03 CST 2018
     */
    public void setJobGroup(String jobGroup) {
        this.jobGroup = jobGroup == null ? null : jobGroup.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column schedule_job_fail_log.create_time
     *
     * @return the value of schedule_job_fail_log.create_time
     *
     * @mbg.generated Fri May 18 14:47:03 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column schedule_job_fail_log.create_time
     *
     * @param createTime the value for schedule_job_fail_log.create_time
     *
     * @mbg.generated Fri May 18 14:47:03 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column schedule_job_fail_log.reason
     *
     * @return the value of schedule_job_fail_log.reason
     *
     * @mbg.generated Fri May 18 14:47:03 CST 2018
     */
    public String getReason() {
        return reason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column schedule_job_fail_log.reason
     *
     * @param reason the value for schedule_job_fail_log.reason
     *
     * @mbg.generated Fri May 18 14:47:03 CST 2018
     */
    public void setReason(String reason) {
        this.reason = reason == null ? null : reason.trim();
    }
}