package com.artqiyi.tanqiu.job.domain;

import java.util.Date;

import com.artqiyi.tanqiu.common.util.JSONUtil;

public class ScheduleJob {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column schedule_job.id
     *
     * @mbg.generated Thu May 10 14:15:14 CST 2018
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column schedule_job.job_name
     *
     * @mbg.generated Thu May 10 14:15:14 CST 2018
     */
    private String jobName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column schedule_job.job_group
     *
     * @mbg.generated Thu May 10 14:15:14 CST 2018
     */
    private String jobGroup;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column schedule_job.cron_expression
     *
     * @mbg.generated Thu May 10 14:15:14 CST 2018
     */
    private String cronExpression;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column schedule_job.is_concurrent
     *
     * @mbg.generated Thu May 10 14:15:14 CST 2018
     */
    private Boolean isConcurrent;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column schedule_job.is_springBean
     *
     * @mbg.generated Thu May 10 14:15:14 CST 2018
     */
    private Boolean isSpringbean;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column schedule_job.target_object
     *
     * @mbg.generated Thu May 10 14:15:14 CST 2018
     */
    private String targetObject;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column schedule_job.target_method
     *
     * @mbg.generated Thu May 10 14:15:14 CST 2018
     */
    private String targetMethod;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column schedule_job.clazz_name
     *
     * @mbg.generated Thu May 10 14:15:14 CST 2018
     */
    private String clazzName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column schedule_job.arguments
     *
     * @mbg.generated Thu May 10 14:15:14 CST 2018
     */
    private String arguments;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column schedule_job.jobStatus
     *
     * @mbg.generated Thu May 10 14:15:14 CST 2018
     */
    private Short jobstatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column schedule_job.description
     *
     * @mbg.generated Thu May 10 14:15:14 CST 2018
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column schedule_job.create_time
     *
     * @mbg.generated Thu May 10 14:15:14 CST 2018
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column schedule_job.update_time
     *
     * @mbg.generated Thu May 10 14:15:14 CST 2018
     */
    private Date updateTime;

    private Object param;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column schedule_job.id
     *
     * @return the value of schedule_job.id
     *
     * @mbg.generated Thu May 10 14:15:14 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column schedule_job.id
     *
     * @param id the value for schedule_job.id
     *
     * @mbg.generated Thu May 10 14:15:14 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column schedule_job.job_name
     *
     * @return the value of schedule_job.job_name
     *
     * @mbg.generated Thu May 10 14:15:14 CST 2018
     */
    public String getJobName() {
        return jobName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column schedule_job.job_name
     *
     * @param jobName the value for schedule_job.job_name
     *
     * @mbg.generated Thu May 10 14:15:14 CST 2018
     */
    public void setJobName(String jobName) {
        this.jobName = jobName == null ? null : jobName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column schedule_job.job_group
     *
     * @return the value of schedule_job.job_group
     *
     * @mbg.generated Thu May 10 14:15:14 CST 2018
     */
    public String getJobGroup() {
        return jobGroup;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column schedule_job.job_group
     *
     * @param jobGroup the value for schedule_job.job_group
     *
     * @mbg.generated Thu May 10 14:15:14 CST 2018
     */
    public void setJobGroup(String jobGroup) {
        this.jobGroup = jobGroup == null ? null : jobGroup.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column schedule_job.cron_expression
     *
     * @return the value of schedule_job.cron_expression
     *
     * @mbg.generated Thu May 10 14:15:14 CST 2018
     */
    public String getCronExpression() {
        return cronExpression;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column schedule_job.cron_expression
     *
     * @param cronExpression the value for schedule_job.cron_expression
     *
     * @mbg.generated Thu May 10 14:15:14 CST 2018
     */
    public void setCronExpression(String cronExpression) {
        this.cronExpression = cronExpression == null ? null : cronExpression.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column schedule_job.is_concurrent
     *
     * @return the value of schedule_job.is_concurrent
     *
     * @mbg.generated Thu May 10 14:15:14 CST 2018
     */
    public Boolean getIsConcurrent() {
        return isConcurrent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column schedule_job.is_concurrent
     *
     * @param isConcurrent the value for schedule_job.is_concurrent
     *
     * @mbg.generated Thu May 10 14:15:14 CST 2018
     */
    public void setIsConcurrent(Boolean isConcurrent) {
        this.isConcurrent = isConcurrent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column schedule_job.is_springBean
     *
     * @return the value of schedule_job.is_springBean
     *
     * @mbg.generated Thu May 10 14:15:14 CST 2018
     */
    public Boolean getIsSpringbean() {
        return isSpringbean;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column schedule_job.is_springBean
     *
     * @param isSpringbean the value for schedule_job.is_springBean
     *
     * @mbg.generated Thu May 10 14:15:14 CST 2018
     */
    public void setIsSpringbean(Boolean isSpringbean) {
        this.isSpringbean = isSpringbean;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column schedule_job.target_object
     *
     * @return the value of schedule_job.target_object
     *
     * @mbg.generated Thu May 10 14:15:14 CST 2018
     */
    public String getTargetObject() {
        return targetObject;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column schedule_job.target_object
     *
     * @param targetObject the value for schedule_job.target_object
     *
     * @mbg.generated Thu May 10 14:15:14 CST 2018
     */
    public void setTargetObject(String targetObject) {
        this.targetObject = targetObject == null ? null : targetObject.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column schedule_job.target_method
     *
     * @return the value of schedule_job.target_method
     *
     * @mbg.generated Thu May 10 14:15:14 CST 2018
     */
    public String getTargetMethod() {
        return targetMethod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column schedule_job.target_method
     *
     * @param targetMethod the value for schedule_job.target_method
     *
     * @mbg.generated Thu May 10 14:15:14 CST 2018
     */
    public void setTargetMethod(String targetMethod) {
        this.targetMethod = targetMethod == null ? null : targetMethod.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column schedule_job.clazz_name
     *
     * @return the value of schedule_job.clazz_name
     *
     * @mbg.generated Thu May 10 14:15:14 CST 2018
     */
    public String getClazzName() {
        return clazzName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column schedule_job.clazz_name
     *
     * @param clazzName the value for schedule_job.clazz_name
     *
     * @mbg.generated Thu May 10 14:15:14 CST 2018
     */
    public void setClazzName(String clazzName) {
        this.clazzName = clazzName == null ? null : clazzName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column schedule_job.arguments
     *
     * @return the value of schedule_job.arguments
     *
     * @mbg.generated Thu May 10 14:15:14 CST 2018
     */
    public String getArguments() {
        return arguments;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column schedule_job.arguments
     *
     * @param arguments the value for schedule_job.arguments
     *
     * @mbg.generated Thu May 10 14:15:14 CST 2018
     */
    public void setArguments(String arguments) {
        this.arguments = arguments == null ? null : arguments.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column schedule_job.jobStatus
     *
     * @return the value of schedule_job.jobStatus
     *
     * @mbg.generated Thu May 10 14:15:14 CST 2018
     */
    public Short getJobstatus() {
        return jobstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column schedule_job.jobStatus
     *
     * @param jobstatus the value for schedule_job.jobStatus
     *
     * @mbg.generated Thu May 10 14:15:14 CST 2018
     */
    public void setJobstatus(Short jobstatus) {
        this.jobstatus = jobstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column schedule_job.description
     *
     * @return the value of schedule_job.description
     *
     * @mbg.generated Thu May 10 14:15:14 CST 2018
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column schedule_job.description
     *
     * @param description the value for schedule_job.description
     *
     * @mbg.generated Thu May 10 14:15:14 CST 2018
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column schedule_job.create_time
     *
     * @return the value of schedule_job.create_time
     *
     * @mbg.generated Thu May 10 14:15:14 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column schedule_job.create_time
     *
     * @param createTime the value for schedule_job.create_time
     *
     * @mbg.generated Thu May 10 14:15:14 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column schedule_job.update_time
     *
     * @return the value of schedule_job.update_time
     *
     * @mbg.generated Thu May 10 14:15:14 CST 2018
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column schedule_job.update_time
     *
     * @param updateTime the value for schedule_job.update_time
     *
     * @mbg.generated Thu May 10 14:15:14 CST 2018
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    public Object getParam() {
        return param;
    }

    public void setParam(Object param) {
        this.param = param;
        this.arguments= JSONUtil.toJson(param).toString();
    }
}