package com.artqiyi.tanqiu.user.domain;

import java.util.Date;

public class UserShare {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_share.share_id
     *
     * @mbg.generated Fri Jul 06 17:03:18 CST 2018
     */
    private Long shareId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_share.user_id
     *
     * @mbg.generated Fri Jul 06 17:03:18 CST 2018
     */
    private Long userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_share.share_title
     *
     * @mbg.generated Fri Jul 06 17:03:18 CST 2018
     */
    private String shareTitle;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_share.share_desc
     *
     * @mbg.generated Fri Jul 06 17:03:18 CST 2018
     */
    private String shareDesc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_share.share_link
     *
     * @mbg.generated Fri Jul 06 17:03:18 CST 2018
     */
    private String shareLink;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_share.share_img_url
     *
     * @mbg.generated Fri Jul 06 17:03:18 CST 2018
     */
    private String shareImgUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_share.share_type
     *
     * @mbg.generated Fri Jul 06 17:03:18 CST 2018
     */
    private String shareType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_share.content_type
     *
     * @mbg.generated Fri Jul 06 17:03:18 CST 2018
     */
    private Short contentType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_share.content_sub_type
     *
     * @mbg.generated Fri Jul 06 17:03:18 CST 2018
     */
    private Short contentSubType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_share.data_url
     *
     * @mbg.generated Fri Jul 06 17:03:18 CST 2018
     */
    private String dataUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_share.create_time
     *
     * @mbg.generated Fri Jul 06 17:03:18 CST 2018
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_share.share_id
     *
     * @return the value of user_share.share_id
     *
     * @mbg.generated Fri Jul 06 17:03:18 CST 2018
     */
    public Long getShareId() {
        return shareId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_share.share_id
     *
     * @param shareId the value for user_share.share_id
     *
     * @mbg.generated Fri Jul 06 17:03:18 CST 2018
     */
    public void setShareId(Long shareId) {
        this.shareId = shareId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_share.user_id
     *
     * @return the value of user_share.user_id
     *
     * @mbg.generated Fri Jul 06 17:03:18 CST 2018
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_share.user_id
     *
     * @param userId the value for user_share.user_id
     *
     * @mbg.generated Fri Jul 06 17:03:18 CST 2018
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_share.share_title
     *
     * @return the value of user_share.share_title
     *
     * @mbg.generated Fri Jul 06 17:03:18 CST 2018
     */
    public String getShareTitle() {
        return shareTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_share.share_title
     *
     * @param shareTitle the value for user_share.share_title
     *
     * @mbg.generated Fri Jul 06 17:03:18 CST 2018
     */
    public void setShareTitle(String shareTitle) {
        this.shareTitle = shareTitle == null ? null : shareTitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_share.share_desc
     *
     * @return the value of user_share.share_desc
     *
     * @mbg.generated Fri Jul 06 17:03:18 CST 2018
     */
    public String getShareDesc() {
        return shareDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_share.share_desc
     *
     * @param shareDesc the value for user_share.share_desc
     *
     * @mbg.generated Fri Jul 06 17:03:18 CST 2018
     */
    public void setShareDesc(String shareDesc) {
        this.shareDesc = shareDesc == null ? null : shareDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_share.share_link
     *
     * @return the value of user_share.share_link
     *
     * @mbg.generated Fri Jul 06 17:03:18 CST 2018
     */
    public String getShareLink() {
        return shareLink;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_share.share_link
     *
     * @param shareLink the value for user_share.share_link
     *
     * @mbg.generated Fri Jul 06 17:03:18 CST 2018
     */
    public void setShareLink(String shareLink) {
        this.shareLink = shareLink == null ? null : shareLink.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_share.share_img_url
     *
     * @return the value of user_share.share_img_url
     *
     * @mbg.generated Fri Jul 06 17:03:18 CST 2018
     */
    public String getShareImgUrl() {
        return shareImgUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_share.share_img_url
     *
     * @param shareImgUrl the value for user_share.share_img_url
     *
     * @mbg.generated Fri Jul 06 17:03:18 CST 2018
     */
    public void setShareImgUrl(String shareImgUrl) {
        this.shareImgUrl = shareImgUrl == null ? null : shareImgUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_share.share_type
     *
     * @return the value of user_share.share_type
     *
     * @mbg.generated Fri Jul 06 17:03:18 CST 2018
     */
    public String getShareType() {
        return shareType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_share.share_type
     *
     * @param shareType the value for user_share.share_type
     *
     * @mbg.generated Fri Jul 06 17:03:18 CST 2018
     */
    public void setShareType(String shareType) {
        this.shareType = shareType == null ? null : shareType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_share.content_type
     *
     * @return the value of user_share.content_type
     *
     * @mbg.generated Fri Jul 06 17:03:18 CST 2018
     */
    public Short getContentType() {
        return contentType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_share.content_type
     *
     * @param contentType the value for user_share.content_type
     *
     * @mbg.generated Fri Jul 06 17:03:18 CST 2018
     */
    public void setContentType(Short contentType) {
        this.contentType = contentType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_share.content_sub_type
     *
     * @return the value of user_share.content_sub_type
     *
     * @mbg.generated Fri Jul 06 17:03:18 CST 2018
     */
    public Short getContentSubType() {
        return contentSubType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_share.content_sub_type
     *
     * @param contentSubType the value for user_share.content_sub_type
     *
     * @mbg.generated Fri Jul 06 17:03:18 CST 2018
     */
    public void setContentSubType(Short contentSubType) {
        this.contentSubType = contentSubType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_share.data_url
     *
     * @return the value of user_share.data_url
     *
     * @mbg.generated Fri Jul 06 17:03:18 CST 2018
     */
    public String getDataUrl() {
        return dataUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_share.data_url
     *
     * @param dataUrl the value for user_share.data_url
     *
     * @mbg.generated Fri Jul 06 17:03:18 CST 2018
     */
    public void setDataUrl(String dataUrl) {
        this.dataUrl = dataUrl == null ? null : dataUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_share.create_time
     *
     * @return the value of user_share.create_time
     *
     * @mbg.generated Fri Jul 06 17:03:18 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_share.create_time
     *
     * @param createTime the value for user_share.create_time
     *
     * @mbg.generated Fri Jul 06 17:03:18 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}