package com.artqiyi.tanqiu.game.domain;

import java.util.Date;

public class GameSinglePrize {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column game_single_prize.id
     *
     * @mbg.generated Thu Jul 05 18:45:18 CST 2018
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column game_single_prize.min_point
     *
     * @mbg.generated Thu Jul 05 18:45:18 CST 2018
     */
    private Integer minPoint;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column game_single_prize.max_point
     *
     * @mbg.generated Thu Jul 05 18:45:18 CST 2018
     */
    private Integer maxPoint;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column game_single_prize.prize_coin
     *
     * @mbg.generated Thu Jul 05 18:45:18 CST 2018
     */
    private Integer prizeCoin;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column game_single_prize.deleted
     *
     * @mbg.generated Thu Jul 05 18:45:18 CST 2018
     */
    private Short deleted;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column game_single_prize.create_time
     *
     * @mbg.generated Thu Jul 05 18:45:18 CST 2018
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column game_single_prize.create_id
     *
     * @mbg.generated Thu Jul 05 18:45:18 CST 2018
     */
    private Long createId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column game_single_prize.update_time
     *
     * @mbg.generated Thu Jul 05 18:45:18 CST 2018
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column game_single_prize.update_id
     *
     * @mbg.generated Thu Jul 05 18:45:18 CST 2018
     */
    private Long updateId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column game_single_prize.id
     *
     * @return the value of game_single_prize.id
     *
     * @mbg.generated Thu Jul 05 18:45:18 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column game_single_prize.id
     *
     * @param id the value for game_single_prize.id
     *
     * @mbg.generated Thu Jul 05 18:45:18 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column game_single_prize.min_point
     *
     * @return the value of game_single_prize.min_point
     *
     * @mbg.generated Thu Jul 05 18:45:18 CST 2018
     */
    public Integer getMinPoint() {
        return minPoint;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column game_single_prize.min_point
     *
     * @param minPoint the value for game_single_prize.min_point
     *
     * @mbg.generated Thu Jul 05 18:45:18 CST 2018
     */
    public void setMinPoint(Integer minPoint) {
        this.minPoint = minPoint;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column game_single_prize.max_point
     *
     * @return the value of game_single_prize.max_point
     *
     * @mbg.generated Thu Jul 05 18:45:18 CST 2018
     */
    public Integer getMaxPoint() {
        return maxPoint;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column game_single_prize.max_point
     *
     * @param maxPoint the value for game_single_prize.max_point
     *
     * @mbg.generated Thu Jul 05 18:45:18 CST 2018
     */
    public void setMaxPoint(Integer maxPoint) {
        this.maxPoint = maxPoint;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column game_single_prize.prize_coin
     *
     * @return the value of game_single_prize.prize_coin
     *
     * @mbg.generated Thu Jul 05 18:45:18 CST 2018
     */
    public Integer getPrizeCoin() {
        return prizeCoin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column game_single_prize.prize_coin
     *
     * @param prizeCoin the value for game_single_prize.prize_coin
     *
     * @mbg.generated Thu Jul 05 18:45:18 CST 2018
     */
    public void setPrizeCoin(Integer prizeCoin) {
        this.prizeCoin = prizeCoin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column game_single_prize.deleted
     *
     * @return the value of game_single_prize.deleted
     *
     * @mbg.generated Thu Jul 05 18:45:18 CST 2018
     */
    public Short getDeleted() {
        return deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column game_single_prize.deleted
     *
     * @param deleted the value for game_single_prize.deleted
     *
     * @mbg.generated Thu Jul 05 18:45:18 CST 2018
     */
    public void setDeleted(Short deleted) {
        this.deleted = deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column game_single_prize.create_time
     *
     * @return the value of game_single_prize.create_time
     *
     * @mbg.generated Thu Jul 05 18:45:18 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column game_single_prize.create_time
     *
     * @param createTime the value for game_single_prize.create_time
     *
     * @mbg.generated Thu Jul 05 18:45:18 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column game_single_prize.create_id
     *
     * @return the value of game_single_prize.create_id
     *
     * @mbg.generated Thu Jul 05 18:45:18 CST 2018
     */
    public Long getCreateId() {
        return createId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column game_single_prize.create_id
     *
     * @param createId the value for game_single_prize.create_id
     *
     * @mbg.generated Thu Jul 05 18:45:18 CST 2018
     */
    public void setCreateId(Long createId) {
        this.createId = createId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column game_single_prize.update_time
     *
     * @return the value of game_single_prize.update_time
     *
     * @mbg.generated Thu Jul 05 18:45:18 CST 2018
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column game_single_prize.update_time
     *
     * @param updateTime the value for game_single_prize.update_time
     *
     * @mbg.generated Thu Jul 05 18:45:18 CST 2018
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column game_single_prize.update_id
     *
     * @return the value of game_single_prize.update_id
     *
     * @mbg.generated Thu Jul 05 18:45:18 CST 2018
     */
    public Long getUpdateId() {
        return updateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column game_single_prize.update_id
     *
     * @param updateId the value for game_single_prize.update_id
     *
     * @mbg.generated Thu Jul 05 18:45:18 CST 2018
     */
    public void setUpdateId(Long updateId) {
        this.updateId = updateId;
    }
}