package com.artqiyi.tanqiu.game.domain;

import java.util.Date;

public class GameDifficultyConfig {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column game_difficulty_config.id
     *
     * @mbg.generated Mon Jul 23 18:10:11 CST 2018
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column game_difficulty_config.game_model_id
     *
     * @mbg.generated Mon Jul 23 18:10:11 CST 2018
     */
    private Long gameModelId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column game_difficulty_config.game_model_key
     *
     * @mbg.generated Mon Jul 23 18:10:11 CST 2018
     */
    private String gameModelKey;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column game_difficulty_config.game_round
     *
     * @mbg.generated Mon Jul 23 18:10:11 CST 2018
     */
    private Integer gameRound;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column game_difficulty_config.min_row
     *
     * @mbg.generated Mon Jul 23 18:10:11 CST 2018
     */
    private Integer minRow;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column game_difficulty_config.max_row
     *
     * @mbg.generated Mon Jul 23 18:10:11 CST 2018
     */
    private Integer maxRow;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column game_difficulty_config.min_score
     *
     * @mbg.generated Mon Jul 23 18:10:11 CST 2018
     */
    private Integer minScore;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column game_difficulty_config.max_score
     *
     * @mbg.generated Mon Jul 23 18:10:11 CST 2018
     */
    private Integer maxScore;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column game_difficulty_config.total_num
     *
     * @mbg.generated Mon Jul 23 18:10:11 CST 2018
     */
    private Integer totalNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column game_difficulty_config.status
     *
     * @mbg.generated Mon Jul 23 18:10:11 CST 2018
     */
    private Short status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column game_difficulty_config.create_id
     *
     * @mbg.generated Mon Jul 23 18:10:11 CST 2018
     */
    private Long createId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column game_difficulty_config.update_id
     *
     * @mbg.generated Mon Jul 23 18:10:11 CST 2018
     */
    private Long updateId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column game_difficulty_config.create_time
     *
     * @mbg.generated Mon Jul 23 18:10:11 CST 2018
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column game_difficulty_config.update_time
     *
     * @mbg.generated Mon Jul 23 18:10:11 CST 2018
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column game_difficulty_config.id
     *
     * @return the value of game_difficulty_config.id
     *
     * @mbg.generated Mon Jul 23 18:10:11 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column game_difficulty_config.id
     *
     * @param id the value for game_difficulty_config.id
     *
     * @mbg.generated Mon Jul 23 18:10:11 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column game_difficulty_config.game_model_id
     *
     * @return the value of game_difficulty_config.game_model_id
     *
     * @mbg.generated Mon Jul 23 18:10:11 CST 2018
     */
    public Long getGameModelId() {
        return gameModelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column game_difficulty_config.game_model_id
     *
     * @param gameModelId the value for game_difficulty_config.game_model_id
     *
     * @mbg.generated Mon Jul 23 18:10:11 CST 2018
     */
    public void setGameModelId(Long gameModelId) {
        this.gameModelId = gameModelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column game_difficulty_config.game_model_key
     *
     * @return the value of game_difficulty_config.game_model_key
     *
     * @mbg.generated Mon Jul 23 18:10:11 CST 2018
     */
    public String getGameModelKey() {
        return gameModelKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column game_difficulty_config.game_model_key
     *
     * @param gameModelKey the value for game_difficulty_config.game_model_key
     *
     * @mbg.generated Mon Jul 23 18:10:11 CST 2018
     */
    public void setGameModelKey(String gameModelKey) {
        this.gameModelKey = gameModelKey == null ? null : gameModelKey.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column game_difficulty_config.game_round
     *
     * @return the value of game_difficulty_config.game_round
     *
     * @mbg.generated Mon Jul 23 18:10:11 CST 2018
     */
    public Integer getGameRound() {
        return gameRound;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column game_difficulty_config.game_round
     *
     * @param gameRound the value for game_difficulty_config.game_round
     *
     * @mbg.generated Mon Jul 23 18:10:11 CST 2018
     */
    public void setGameRound(Integer gameRound) {
        this.gameRound = gameRound;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column game_difficulty_config.min_row
     *
     * @return the value of game_difficulty_config.min_row
     *
     * @mbg.generated Mon Jul 23 18:10:11 CST 2018
     */
    public Integer getMinRow() {
        return minRow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column game_difficulty_config.min_row
     *
     * @param minRow the value for game_difficulty_config.min_row
     *
     * @mbg.generated Mon Jul 23 18:10:11 CST 2018
     */
    public void setMinRow(Integer minRow) {
        this.minRow = minRow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column game_difficulty_config.max_row
     *
     * @return the value of game_difficulty_config.max_row
     *
     * @mbg.generated Mon Jul 23 18:10:11 CST 2018
     */
    public Integer getMaxRow() {
        return maxRow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column game_difficulty_config.max_row
     *
     * @param maxRow the value for game_difficulty_config.max_row
     *
     * @mbg.generated Mon Jul 23 18:10:11 CST 2018
     */
    public void setMaxRow(Integer maxRow) {
        this.maxRow = maxRow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column game_difficulty_config.min_score
     *
     * @return the value of game_difficulty_config.min_score
     *
     * @mbg.generated Mon Jul 23 18:10:11 CST 2018
     */
    public Integer getMinScore() {
        return minScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column game_difficulty_config.min_score
     *
     * @param minScore the value for game_difficulty_config.min_score
     *
     * @mbg.generated Mon Jul 23 18:10:11 CST 2018
     */
    public void setMinScore(Integer minScore) {
        this.minScore = minScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column game_difficulty_config.max_score
     *
     * @return the value of game_difficulty_config.max_score
     *
     * @mbg.generated Mon Jul 23 18:10:11 CST 2018
     */
    public Integer getMaxScore() {
        return maxScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column game_difficulty_config.max_score
     *
     * @param maxScore the value for game_difficulty_config.max_score
     *
     * @mbg.generated Mon Jul 23 18:10:11 CST 2018
     */
    public void setMaxScore(Integer maxScore) {
        this.maxScore = maxScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column game_difficulty_config.total_num
     *
     * @return the value of game_difficulty_config.total_num
     *
     * @mbg.generated Mon Jul 23 18:10:11 CST 2018
     */
    public Integer getTotalNum() {
        return totalNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column game_difficulty_config.total_num
     *
     * @param totalNum the value for game_difficulty_config.total_num
     *
     * @mbg.generated Mon Jul 23 18:10:11 CST 2018
     */
    public void setTotalNum(Integer totalNum) {
        this.totalNum = totalNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column game_difficulty_config.status
     *
     * @return the value of game_difficulty_config.status
     *
     * @mbg.generated Mon Jul 23 18:10:11 CST 2018
     */
    public Short getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column game_difficulty_config.status
     *
     * @param status the value for game_difficulty_config.status
     *
     * @mbg.generated Mon Jul 23 18:10:11 CST 2018
     */
    public void setStatus(Short status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column game_difficulty_config.create_id
     *
     * @return the value of game_difficulty_config.create_id
     *
     * @mbg.generated Mon Jul 23 18:10:11 CST 2018
     */
    public Long getCreateId() {
        return createId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column game_difficulty_config.create_id
     *
     * @param createId the value for game_difficulty_config.create_id
     *
     * @mbg.generated Mon Jul 23 18:10:11 CST 2018
     */
    public void setCreateId(Long createId) {
        this.createId = createId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column game_difficulty_config.update_id
     *
     * @return the value of game_difficulty_config.update_id
     *
     * @mbg.generated Mon Jul 23 18:10:11 CST 2018
     */
    public Long getUpdateId() {
        return updateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column game_difficulty_config.update_id
     *
     * @param updateId the value for game_difficulty_config.update_id
     *
     * @mbg.generated Mon Jul 23 18:10:11 CST 2018
     */
    public void setUpdateId(Long updateId) {
        this.updateId = updateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column game_difficulty_config.create_time
     *
     * @return the value of game_difficulty_config.create_time
     *
     * @mbg.generated Mon Jul 23 18:10:11 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column game_difficulty_config.create_time
     *
     * @param createTime the value for game_difficulty_config.create_time
     *
     * @mbg.generated Mon Jul 23 18:10:11 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column game_difficulty_config.update_time
     *
     * @return the value of game_difficulty_config.update_time
     *
     * @mbg.generated Mon Jul 23 18:10:11 CST 2018
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column game_difficulty_config.update_time
     *
     * @param updateTime the value for game_difficulty_config.update_time
     *
     * @mbg.generated Mon Jul 23 18:10:11 CST 2018
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}