package com.artqiyi.tanqiu.game.domain;

import java.util.Date;

public class GameRedpacketPrizeConfig {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column game_redpacket_prize_config.id
     *
     * @mbg.generated Mon Jul 23 18:10:11 CST 2018
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column game_redpacket_prize_config.game_model_id
     *
     * @mbg.generated Mon Jul 23 18:10:11 CST 2018
     */
    private Long gameModelId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column game_redpacket_prize_config.game_model_key
     *
     * @mbg.generated Mon Jul 23 18:10:11 CST 2018
     */
    private String gameModelKey;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column game_redpacket_prize_config.rank
     *
     * @mbg.generated Mon Jul 23 18:10:11 CST 2018
     */
    private Integer rank;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column game_redpacket_prize_config.prize_type_code
     *
     * @mbg.generated Mon Jul 23 18:10:11 CST 2018
     */
    private String prizeTypeCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column game_redpacket_prize_config.prize_num
     *
     * @mbg.generated Mon Jul 23 18:10:11 CST 2018
     */
    private Integer prizeNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column game_redpacket_prize_config.status
     *
     * @mbg.generated Mon Jul 23 18:10:11 CST 2018
     */
    private Short status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column game_redpacket_prize_config.deleted
     *
     * @mbg.generated Mon Jul 23 18:10:11 CST 2018
     */
    private Boolean deleted;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column game_redpacket_prize_config.creator_id
     *
     * @mbg.generated Mon Jul 23 18:10:11 CST 2018
     */
    private Long creatorId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column game_redpacket_prize_config.create_time
     *
     * @mbg.generated Mon Jul 23 18:10:11 CST 2018
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column game_redpacket_prize_config.updator_id
     *
     * @mbg.generated Mon Jul 23 18:10:11 CST 2018
     */
    private Long updatorId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column game_redpacket_prize_config.update_time
     *
     * @mbg.generated Mon Jul 23 18:10:11 CST 2018
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column game_redpacket_prize_config.id
     *
     * @return the value of game_redpacket_prize_config.id
     *
     * @mbg.generated Mon Jul 23 18:10:11 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column game_redpacket_prize_config.id
     *
     * @param id the value for game_redpacket_prize_config.id
     *
     * @mbg.generated Mon Jul 23 18:10:11 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column game_redpacket_prize_config.game_model_id
     *
     * @return the value of game_redpacket_prize_config.game_model_id
     *
     * @mbg.generated Mon Jul 23 18:10:11 CST 2018
     */
    public Long getGameModelId() {
        return gameModelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column game_redpacket_prize_config.game_model_id
     *
     * @param gameModelId the value for game_redpacket_prize_config.game_model_id
     *
     * @mbg.generated Mon Jul 23 18:10:11 CST 2018
     */
    public void setGameModelId(Long gameModelId) {
        this.gameModelId = gameModelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column game_redpacket_prize_config.game_model_key
     *
     * @return the value of game_redpacket_prize_config.game_model_key
     *
     * @mbg.generated Mon Jul 23 18:10:11 CST 2018
     */
    public String getGameModelKey() {
        return gameModelKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column game_redpacket_prize_config.game_model_key
     *
     * @param gameModelKey the value for game_redpacket_prize_config.game_model_key
     *
     * @mbg.generated Mon Jul 23 18:10:11 CST 2018
     */
    public void setGameModelKey(String gameModelKey) {
        this.gameModelKey = gameModelKey == null ? null : gameModelKey.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column game_redpacket_prize_config.rank
     *
     * @return the value of game_redpacket_prize_config.rank
     *
     * @mbg.generated Mon Jul 23 18:10:11 CST 2018
     */
    public Integer getRank() {
        return rank;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column game_redpacket_prize_config.rank
     *
     * @param rank the value for game_redpacket_prize_config.rank
     *
     * @mbg.generated Mon Jul 23 18:10:11 CST 2018
     */
    public void setRank(Integer rank) {
        this.rank = rank;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column game_redpacket_prize_config.prize_type_code
     *
     * @return the value of game_redpacket_prize_config.prize_type_code
     *
     * @mbg.generated Mon Jul 23 18:10:11 CST 2018
     */
    public String getPrizeTypeCode() {
        return prizeTypeCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column game_redpacket_prize_config.prize_type_code
     *
     * @param prizeTypeCode the value for game_redpacket_prize_config.prize_type_code
     *
     * @mbg.generated Mon Jul 23 18:10:11 CST 2018
     */
    public void setPrizeTypeCode(String prizeTypeCode) {
        this.prizeTypeCode = prizeTypeCode == null ? null : prizeTypeCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column game_redpacket_prize_config.prize_num
     *
     * @return the value of game_redpacket_prize_config.prize_num
     *
     * @mbg.generated Mon Jul 23 18:10:11 CST 2018
     */
    public Integer getPrizeNum() {
        return prizeNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column game_redpacket_prize_config.prize_num
     *
     * @param prizeNum the value for game_redpacket_prize_config.prize_num
     *
     * @mbg.generated Mon Jul 23 18:10:11 CST 2018
     */
    public void setPrizeNum(Integer prizeNum) {
        this.prizeNum = prizeNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column game_redpacket_prize_config.status
     *
     * @return the value of game_redpacket_prize_config.status
     *
     * @mbg.generated Mon Jul 23 18:10:11 CST 2018
     */
    public Short getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column game_redpacket_prize_config.status
     *
     * @param status the value for game_redpacket_prize_config.status
     *
     * @mbg.generated Mon Jul 23 18:10:11 CST 2018
     */
    public void setStatus(Short status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column game_redpacket_prize_config.deleted
     *
     * @return the value of game_redpacket_prize_config.deleted
     *
     * @mbg.generated Mon Jul 23 18:10:11 CST 2018
     */
    public Boolean getDeleted() {
        return deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column game_redpacket_prize_config.deleted
     *
     * @param deleted the value for game_redpacket_prize_config.deleted
     *
     * @mbg.generated Mon Jul 23 18:10:11 CST 2018
     */
    public void setDeleted(Boolean deleted) {
        this.deleted = deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column game_redpacket_prize_config.creator_id
     *
     * @return the value of game_redpacket_prize_config.creator_id
     *
     * @mbg.generated Mon Jul 23 18:10:11 CST 2018
     */
    public Long getCreatorId() {
        return creatorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column game_redpacket_prize_config.creator_id
     *
     * @param creatorId the value for game_redpacket_prize_config.creator_id
     *
     * @mbg.generated Mon Jul 23 18:10:11 CST 2018
     */
    public void setCreatorId(Long creatorId) {
        this.creatorId = creatorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column game_redpacket_prize_config.create_time
     *
     * @return the value of game_redpacket_prize_config.create_time
     *
     * @mbg.generated Mon Jul 23 18:10:11 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column game_redpacket_prize_config.create_time
     *
     * @param createTime the value for game_redpacket_prize_config.create_time
     *
     * @mbg.generated Mon Jul 23 18:10:11 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column game_redpacket_prize_config.updator_id
     *
     * @return the value of game_redpacket_prize_config.updator_id
     *
     * @mbg.generated Mon Jul 23 18:10:11 CST 2018
     */
    public Long getUpdatorId() {
        return updatorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column game_redpacket_prize_config.updator_id
     *
     * @param updatorId the value for game_redpacket_prize_config.updator_id
     *
     * @mbg.generated Mon Jul 23 18:10:11 CST 2018
     */
    public void setUpdatorId(Long updatorId) {
        this.updatorId = updatorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column game_redpacket_prize_config.update_time
     *
     * @return the value of game_redpacket_prize_config.update_time
     *
     * @mbg.generated Mon Jul 23 18:10:11 CST 2018
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column game_redpacket_prize_config.update_time
     *
     * @param updateTime the value for game_redpacket_prize_config.update_time
     *
     * @mbg.generated Mon Jul 23 18:10:11 CST 2018
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}