package com.artqiyi.tanqiu.game.domain;

import java.util.Date;

public class GameRedpacketUserRecords {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column game_redpacket_user_records.id
     *
     * @mbg.generated Tue Jul 24 18:34:57 CST 2018
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column game_redpacket_user_records.game_model_id
     *
     * @mbg.generated Tue Jul 24 18:34:57 CST 2018
     */
    private Long gameModelId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column game_redpacket_user_records.game_model_key
     *
     * @mbg.generated Tue Jul 24 18:34:57 CST 2018
     */
    private String gameModelKey;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column game_redpacket_user_records.game_no
     *
     * @mbg.generated Tue Jul 24 18:34:57 CST 2018
     */
    private String gameNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column game_redpacket_user_records.user_id
     *
     * @mbg.generated Tue Jul 24 18:34:57 CST 2018
     */
    private Long userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column game_redpacket_user_records.nick_name
     *
     * @mbg.generated Tue Jul 24 18:34:57 CST 2018
     */
    private String nickName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column game_redpacket_user_records.head_url
     *
     * @mbg.generated Tue Jul 24 18:34:57 CST 2018
     */
    private String headUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column game_redpacket_user_records.score
     *
     * @mbg.generated Tue Jul 24 18:34:57 CST 2018
     */
    private Integer score;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column game_redpacket_user_records.is_cheated
     *
     * @mbg.generated Tue Jul 24 18:34:57 CST 2018
     */
    private Boolean isCheated;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column game_redpacket_user_records.is_robot
     *
     * @mbg.generated Tue Jul 24 18:34:57 CST 2018
     */
    private Boolean isRobot;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column game_redpacket_user_records.note
     *
     * @mbg.generated Tue Jul 24 18:34:57 CST 2018
     */
    private String note;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column game_redpacket_user_records.create_time
     *
     * @mbg.generated Tue Jul 24 18:34:57 CST 2018
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column game_redpacket_user_records.update_time
     *
     * @mbg.generated Tue Jul 24 18:34:57 CST 2018
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column game_redpacket_user_records.id
     *
     * @return the value of game_redpacket_user_records.id
     *
     * @mbg.generated Tue Jul 24 18:34:57 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column game_redpacket_user_records.id
     *
     * @param id the value for game_redpacket_user_records.id
     *
     * @mbg.generated Tue Jul 24 18:34:57 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column game_redpacket_user_records.game_model_id
     *
     * @return the value of game_redpacket_user_records.game_model_id
     *
     * @mbg.generated Tue Jul 24 18:34:57 CST 2018
     */
    public Long getGameModelId() {
        return gameModelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column game_redpacket_user_records.game_model_id
     *
     * @param gameModelId the value for game_redpacket_user_records.game_model_id
     *
     * @mbg.generated Tue Jul 24 18:34:57 CST 2018
     */
    public void setGameModelId(Long gameModelId) {
        this.gameModelId = gameModelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column game_redpacket_user_records.game_model_key
     *
     * @return the value of game_redpacket_user_records.game_model_key
     *
     * @mbg.generated Tue Jul 24 18:34:57 CST 2018
     */
    public String getGameModelKey() {
        return gameModelKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column game_redpacket_user_records.game_model_key
     *
     * @param gameModelKey the value for game_redpacket_user_records.game_model_key
     *
     * @mbg.generated Tue Jul 24 18:34:57 CST 2018
     */
    public void setGameModelKey(String gameModelKey) {
        this.gameModelKey = gameModelKey == null ? null : gameModelKey.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column game_redpacket_user_records.game_no
     *
     * @return the value of game_redpacket_user_records.game_no
     *
     * @mbg.generated Tue Jul 24 18:34:57 CST 2018
     */
    public String getGameNo() {
        return gameNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column game_redpacket_user_records.game_no
     *
     * @param gameNo the value for game_redpacket_user_records.game_no
     *
     * @mbg.generated Tue Jul 24 18:34:57 CST 2018
     */
    public void setGameNo(String gameNo) {
        this.gameNo = gameNo == null ? null : gameNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column game_redpacket_user_records.user_id
     *
     * @return the value of game_redpacket_user_records.user_id
     *
     * @mbg.generated Tue Jul 24 18:34:57 CST 2018
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column game_redpacket_user_records.user_id
     *
     * @param userId the value for game_redpacket_user_records.user_id
     *
     * @mbg.generated Tue Jul 24 18:34:57 CST 2018
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column game_redpacket_user_records.nick_name
     *
     * @return the value of game_redpacket_user_records.nick_name
     *
     * @mbg.generated Tue Jul 24 18:34:57 CST 2018
     */
    public String getNickName() {
        return nickName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column game_redpacket_user_records.nick_name
     *
     * @param nickName the value for game_redpacket_user_records.nick_name
     *
     * @mbg.generated Tue Jul 24 18:34:57 CST 2018
     */
    public void setNickName(String nickName) {
        this.nickName = nickName == null ? null : nickName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column game_redpacket_user_records.head_url
     *
     * @return the value of game_redpacket_user_records.head_url
     *
     * @mbg.generated Tue Jul 24 18:34:57 CST 2018
     */
    public String getHeadUrl() {
        return headUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column game_redpacket_user_records.head_url
     *
     * @param headUrl the value for game_redpacket_user_records.head_url
     *
     * @mbg.generated Tue Jul 24 18:34:57 CST 2018
     */
    public void setHeadUrl(String headUrl) {
        this.headUrl = headUrl == null ? null : headUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column game_redpacket_user_records.score
     *
     * @return the value of game_redpacket_user_records.score
     *
     * @mbg.generated Tue Jul 24 18:34:57 CST 2018
     */
    public Integer getScore() {
        return score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column game_redpacket_user_records.score
     *
     * @param score the value for game_redpacket_user_records.score
     *
     * @mbg.generated Tue Jul 24 18:34:57 CST 2018
     */
    public void setScore(Integer score) {
        this.score = score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column game_redpacket_user_records.is_cheated
     *
     * @return the value of game_redpacket_user_records.is_cheated
     *
     * @mbg.generated Tue Jul 24 18:34:57 CST 2018
     */
    public Boolean getIsCheated() {
        return isCheated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column game_redpacket_user_records.is_cheated
     *
     * @param isCheated the value for game_redpacket_user_records.is_cheated
     *
     * @mbg.generated Tue Jul 24 18:34:57 CST 2018
     */
    public void setIsCheated(Boolean isCheated) {
        this.isCheated = isCheated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column game_redpacket_user_records.is_robot
     *
     * @return the value of game_redpacket_user_records.is_robot
     *
     * @mbg.generated Tue Jul 24 18:34:57 CST 2018
     */
    public Boolean getIsRobot() {
        return isRobot;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column game_redpacket_user_records.is_robot
     *
     * @param isRobot the value for game_redpacket_user_records.is_robot
     *
     * @mbg.generated Tue Jul 24 18:34:57 CST 2018
     */
    public void setIsRobot(Boolean isRobot) {
        this.isRobot = isRobot;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column game_redpacket_user_records.note
     *
     * @return the value of game_redpacket_user_records.note
     *
     * @mbg.generated Tue Jul 24 18:34:57 CST 2018
     */
    public String getNote() {
        return note;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column game_redpacket_user_records.note
     *
     * @param note the value for game_redpacket_user_records.note
     *
     * @mbg.generated Tue Jul 24 18:34:57 CST 2018
     */
    public void setNote(String note) {
        this.note = note == null ? null : note.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column game_redpacket_user_records.create_time
     *
     * @return the value of game_redpacket_user_records.create_time
     *
     * @mbg.generated Tue Jul 24 18:34:57 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column game_redpacket_user_records.create_time
     *
     * @param createTime the value for game_redpacket_user_records.create_time
     *
     * @mbg.generated Tue Jul 24 18:34:57 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column game_redpacket_user_records.update_time
     *
     * @return the value of game_redpacket_user_records.update_time
     *
     * @mbg.generated Tue Jul 24 18:34:57 CST 2018
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column game_redpacket_user_records.update_time
     *
     * @param updateTime the value for game_redpacket_user_records.update_time
     *
     * @mbg.generated Tue Jul 24 18:34:57 CST 2018
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}