package com.artqiyi.tanqiu.game.domain;

import java.util.Date;

public class GameRedpacketRecords {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column game_redpacket_records.id
     *
     * @mbg.generated Mon Jul 23 18:10:11 CST 2018
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column game_redpacket_records.game_model_id
     *
     * @mbg.generated Mon Jul 23 18:10:11 CST 2018
     */
    private Long gameModelId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column game_redpacket_records.game_model_key
     *
     * @mbg.generated Mon Jul 23 18:10:11 CST 2018
     */
    private String gameModelKey;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column game_redpacket_records.game_no
     *
     * @mbg.generated Mon Jul 23 18:10:11 CST 2018
     */
    private String gameNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column game_redpacket_records.game_filed_name
     *
     * @mbg.generated Mon Jul 23 18:10:11 CST 2018
     */
    private String gameFiledName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column game_redpacket_records.total_round
     *
     * @mbg.generated Mon Jul 23 18:10:11 CST 2018
     */
    private Integer totalRound;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column game_redpacket_records.game_data
     *
     * @mbg.generated Mon Jul 23 18:10:11 CST 2018
     */
    private String gameData;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column game_redpacket_records.max_score
     *
     * @mbg.generated Mon Jul 23 18:10:11 CST 2018
     */
    private Integer maxScore;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column game_redpacket_records.contest_num
     *
     * @mbg.generated Mon Jul 23 18:10:11 CST 2018
     */
    private Integer contestNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column game_redpacket_records.cheat_num
     *
     * @mbg.generated Mon Jul 23 18:10:11 CST 2018
     */
    private Integer cheatNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column game_redpacket_records.game_status
     *
     * @mbg.generated Mon Jul 23 18:10:11 CST 2018
     */
    private Short gameStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column game_redpacket_records.start_time
     *
     * @mbg.generated Mon Jul 23 18:10:11 CST 2018
     */
    private Date startTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column game_redpacket_records.end_time
     *
     * @mbg.generated Mon Jul 23 18:10:11 CST 2018
     */
    private Date endTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column game_redpacket_records.create_time
     *
     * @mbg.generated Mon Jul 23 18:10:11 CST 2018
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column game_redpacket_records.update_time
     *
     * @mbg.generated Mon Jul 23 18:10:11 CST 2018
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column game_redpacket_records.id
     *
     * @return the value of game_redpacket_records.id
     *
     * @mbg.generated Mon Jul 23 18:10:11 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column game_redpacket_records.id
     *
     * @param id the value for game_redpacket_records.id
     *
     * @mbg.generated Mon Jul 23 18:10:11 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column game_redpacket_records.game_model_id
     *
     * @return the value of game_redpacket_records.game_model_id
     *
     * @mbg.generated Mon Jul 23 18:10:11 CST 2018
     */
    public Long getGameModelId() {
        return gameModelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column game_redpacket_records.game_model_id
     *
     * @param gameModelId the value for game_redpacket_records.game_model_id
     *
     * @mbg.generated Mon Jul 23 18:10:11 CST 2018
     */
    public void setGameModelId(Long gameModelId) {
        this.gameModelId = gameModelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column game_redpacket_records.game_model_key
     *
     * @return the value of game_redpacket_records.game_model_key
     *
     * @mbg.generated Mon Jul 23 18:10:11 CST 2018
     */
    public String getGameModelKey() {
        return gameModelKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column game_redpacket_records.game_model_key
     *
     * @param gameModelKey the value for game_redpacket_records.game_model_key
     *
     * @mbg.generated Mon Jul 23 18:10:11 CST 2018
     */
    public void setGameModelKey(String gameModelKey) {
        this.gameModelKey = gameModelKey == null ? null : gameModelKey.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column game_redpacket_records.game_no
     *
     * @return the value of game_redpacket_records.game_no
     *
     * @mbg.generated Mon Jul 23 18:10:11 CST 2018
     */
    public String getGameNo() {
        return gameNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column game_redpacket_records.game_no
     *
     * @param gameNo the value for game_redpacket_records.game_no
     *
     * @mbg.generated Mon Jul 23 18:10:11 CST 2018
     */
    public void setGameNo(String gameNo) {
        this.gameNo = gameNo == null ? null : gameNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column game_redpacket_records.game_filed_name
     *
     * @return the value of game_redpacket_records.game_filed_name
     *
     * @mbg.generated Mon Jul 23 18:10:11 CST 2018
     */
    public String getGameFiledName() {
        return gameFiledName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column game_redpacket_records.game_filed_name
     *
     * @param gameFiledName the value for game_redpacket_records.game_filed_name
     *
     * @mbg.generated Mon Jul 23 18:10:11 CST 2018
     */
    public void setGameFiledName(String gameFiledName) {
        this.gameFiledName = gameFiledName == null ? null : gameFiledName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column game_redpacket_records.total_round
     *
     * @return the value of game_redpacket_records.total_round
     *
     * @mbg.generated Mon Jul 23 18:10:11 CST 2018
     */
    public Integer getTotalRound() {
        return totalRound;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column game_redpacket_records.total_round
     *
     * @param totalRound the value for game_redpacket_records.total_round
     *
     * @mbg.generated Mon Jul 23 18:10:11 CST 2018
     */
    public void setTotalRound(Integer totalRound) {
        this.totalRound = totalRound;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column game_redpacket_records.game_data
     *
     * @return the value of game_redpacket_records.game_data
     *
     * @mbg.generated Mon Jul 23 18:10:11 CST 2018
     */
    public String getGameData() {
        return gameData;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column game_redpacket_records.game_data
     *
     * @param gameData the value for game_redpacket_records.game_data
     *
     * @mbg.generated Mon Jul 23 18:10:11 CST 2018
     */
    public void setGameData(String gameData) {
        this.gameData = gameData == null ? null : gameData.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column game_redpacket_records.max_score
     *
     * @return the value of game_redpacket_records.max_score
     *
     * @mbg.generated Mon Jul 23 18:10:11 CST 2018
     */
    public Integer getMaxScore() {
        return maxScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column game_redpacket_records.max_score
     *
     * @param maxScore the value for game_redpacket_records.max_score
     *
     * @mbg.generated Mon Jul 23 18:10:11 CST 2018
     */
    public void setMaxScore(Integer maxScore) {
        this.maxScore = maxScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column game_redpacket_records.contest_num
     *
     * @return the value of game_redpacket_records.contest_num
     *
     * @mbg.generated Mon Jul 23 18:10:11 CST 2018
     */
    public Integer getContestNum() {
        return contestNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column game_redpacket_records.contest_num
     *
     * @param contestNum the value for game_redpacket_records.contest_num
     *
     * @mbg.generated Mon Jul 23 18:10:11 CST 2018
     */
    public void setContestNum(Integer contestNum) {
        this.contestNum = contestNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column game_redpacket_records.cheat_num
     *
     * @return the value of game_redpacket_records.cheat_num
     *
     * @mbg.generated Mon Jul 23 18:10:11 CST 2018
     */
    public Integer getCheatNum() {
        return cheatNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column game_redpacket_records.cheat_num
     *
     * @param cheatNum the value for game_redpacket_records.cheat_num
     *
     * @mbg.generated Mon Jul 23 18:10:11 CST 2018
     */
    public void setCheatNum(Integer cheatNum) {
        this.cheatNum = cheatNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column game_redpacket_records.game_status
     *
     * @return the value of game_redpacket_records.game_status
     *
     * @mbg.generated Mon Jul 23 18:10:11 CST 2018
     */
    public Short getGameStatus() {
        return gameStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column game_redpacket_records.game_status
     *
     * @param gameStatus the value for game_redpacket_records.game_status
     *
     * @mbg.generated Mon Jul 23 18:10:11 CST 2018
     */
    public void setGameStatus(Short gameStatus) {
        this.gameStatus = gameStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column game_redpacket_records.start_time
     *
     * @return the value of game_redpacket_records.start_time
     *
     * @mbg.generated Mon Jul 23 18:10:11 CST 2018
     */
    public Date getStartTime() {
        return startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column game_redpacket_records.start_time
     *
     * @param startTime the value for game_redpacket_records.start_time
     *
     * @mbg.generated Mon Jul 23 18:10:11 CST 2018
     */
    public void setStartTime(Date startTime) {
        this.startTime = startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column game_redpacket_records.end_time
     *
     * @return the value of game_redpacket_records.end_time
     *
     * @mbg.generated Mon Jul 23 18:10:11 CST 2018
     */
    public Date getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column game_redpacket_records.end_time
     *
     * @param endTime the value for game_redpacket_records.end_time
     *
     * @mbg.generated Mon Jul 23 18:10:11 CST 2018
     */
    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column game_redpacket_records.create_time
     *
     * @return the value of game_redpacket_records.create_time
     *
     * @mbg.generated Mon Jul 23 18:10:11 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column game_redpacket_records.create_time
     *
     * @param createTime the value for game_redpacket_records.create_time
     *
     * @mbg.generated Mon Jul 23 18:10:11 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column game_redpacket_records.update_time
     *
     * @return the value of game_redpacket_records.update_time
     *
     * @mbg.generated Mon Jul 23 18:10:11 CST 2018
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column game_redpacket_records.update_time
     *
     * @param updateTime the value for game_redpacket_records.update_time
     *
     * @mbg.generated Mon Jul 23 18:10:11 CST 2018
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}