package com.artqiyi.tanqiu.game.domain;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class RobotVideoConfigExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table robot_video_config
     *
     * @mbg.generated Fri Aug 24 11:36:26 CST 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table robot_video_config
     *
     * @mbg.generated Fri Aug 24 11:36:26 CST 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table robot_video_config
     *
     * @mbg.generated Fri Aug 24 11:36:26 CST 2018
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table robot_video_config
     *
     * @mbg.generated Fri Aug 24 11:36:26 CST 2018
     */
    public RobotVideoConfigExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table robot_video_config
     *
     * @mbg.generated Fri Aug 24 11:36:26 CST 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table robot_video_config
     *
     * @mbg.generated Fri Aug 24 11:36:26 CST 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table robot_video_config
     *
     * @mbg.generated Fri Aug 24 11:36:26 CST 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table robot_video_config
     *
     * @mbg.generated Fri Aug 24 11:36:26 CST 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table robot_video_config
     *
     * @mbg.generated Fri Aug 24 11:36:26 CST 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table robot_video_config
     *
     * @mbg.generated Fri Aug 24 11:36:26 CST 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table robot_video_config
     *
     * @mbg.generated Fri Aug 24 11:36:26 CST 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table robot_video_config
     *
     * @mbg.generated Fri Aug 24 11:36:26 CST 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table robot_video_config
     *
     * @mbg.generated Fri Aug 24 11:36:26 CST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table robot_video_config
     *
     * @mbg.generated Fri Aug 24 11:36:26 CST 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table robot_video_config
     *
     * @mbg.generated Fri Aug 24 11:36:26 CST 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andGameModelIdIsNull() {
            addCriterion("game_model_id is null");
            return (Criteria) this;
        }

        public Criteria andGameModelIdIsNotNull() {
            addCriterion("game_model_id is not null");
            return (Criteria) this;
        }

        public Criteria andGameModelIdEqualTo(Long value) {
            addCriterion("game_model_id =", value, "gameModelId");
            return (Criteria) this;
        }

        public Criteria andGameModelIdNotEqualTo(Long value) {
            addCriterion("game_model_id <>", value, "gameModelId");
            return (Criteria) this;
        }

        public Criteria andGameModelIdGreaterThan(Long value) {
            addCriterion("game_model_id >", value, "gameModelId");
            return (Criteria) this;
        }

        public Criteria andGameModelIdGreaterThanOrEqualTo(Long value) {
            addCriterion("game_model_id >=", value, "gameModelId");
            return (Criteria) this;
        }

        public Criteria andGameModelIdLessThan(Long value) {
            addCriterion("game_model_id <", value, "gameModelId");
            return (Criteria) this;
        }

        public Criteria andGameModelIdLessThanOrEqualTo(Long value) {
            addCriterion("game_model_id <=", value, "gameModelId");
            return (Criteria) this;
        }

        public Criteria andGameModelIdIn(List<Long> values) {
            addCriterion("game_model_id in", values, "gameModelId");
            return (Criteria) this;
        }

        public Criteria andGameModelIdNotIn(List<Long> values) {
            addCriterion("game_model_id not in", values, "gameModelId");
            return (Criteria) this;
        }

        public Criteria andGameModelIdBetween(Long value1, Long value2) {
            addCriterion("game_model_id between", value1, value2, "gameModelId");
            return (Criteria) this;
        }

        public Criteria andGameModelIdNotBetween(Long value1, Long value2) {
            addCriterion("game_model_id not between", value1, value2, "gameModelId");
            return (Criteria) this;
        }

        public Criteria andGameModelKeyIsNull() {
            addCriterion("game_model_key is null");
            return (Criteria) this;
        }

        public Criteria andGameModelKeyIsNotNull() {
            addCriterion("game_model_key is not null");
            return (Criteria) this;
        }

        public Criteria andGameModelKeyEqualTo(String value) {
            addCriterion("game_model_key =", value, "gameModelKey");
            return (Criteria) this;
        }

        public Criteria andGameModelKeyNotEqualTo(String value) {
            addCriterion("game_model_key <>", value, "gameModelKey");
            return (Criteria) this;
        }

        public Criteria andGameModelKeyGreaterThan(String value) {
            addCriterion("game_model_key >", value, "gameModelKey");
            return (Criteria) this;
        }

        public Criteria andGameModelKeyGreaterThanOrEqualTo(String value) {
            addCriterion("game_model_key >=", value, "gameModelKey");
            return (Criteria) this;
        }

        public Criteria andGameModelKeyLessThan(String value) {
            addCriterion("game_model_key <", value, "gameModelKey");
            return (Criteria) this;
        }

        public Criteria andGameModelKeyLessThanOrEqualTo(String value) {
            addCriterion("game_model_key <=", value, "gameModelKey");
            return (Criteria) this;
        }

        public Criteria andGameModelKeyLike(String value) {
            addCriterion("game_model_key like", value, "gameModelKey");
            return (Criteria) this;
        }

        public Criteria andGameModelKeyNotLike(String value) {
            addCriterion("game_model_key not like", value, "gameModelKey");
            return (Criteria) this;
        }

        public Criteria andGameModelKeyIn(List<String> values) {
            addCriterion("game_model_key in", values, "gameModelKey");
            return (Criteria) this;
        }

        public Criteria andGameModelKeyNotIn(List<String> values) {
            addCriterion("game_model_key not in", values, "gameModelKey");
            return (Criteria) this;
        }

        public Criteria andGameModelKeyBetween(String value1, String value2) {
            addCriterion("game_model_key between", value1, value2, "gameModelKey");
            return (Criteria) this;
        }

        public Criteria andGameModelKeyNotBetween(String value1, String value2) {
            addCriterion("game_model_key not between", value1, value2, "gameModelKey");
            return (Criteria) this;
        }

        public Criteria andTurnNumIsNull() {
            addCriterion("turn_num is null");
            return (Criteria) this;
        }

        public Criteria andTurnNumIsNotNull() {
            addCriterion("turn_num is not null");
            return (Criteria) this;
        }

        public Criteria andTurnNumEqualTo(Integer value) {
            addCriterion("turn_num =", value, "turnNum");
            return (Criteria) this;
        }

        public Criteria andTurnNumNotEqualTo(Integer value) {
            addCriterion("turn_num <>", value, "turnNum");
            return (Criteria) this;
        }

        public Criteria andTurnNumGreaterThan(Integer value) {
            addCriterion("turn_num >", value, "turnNum");
            return (Criteria) this;
        }

        public Criteria andTurnNumGreaterThanOrEqualTo(Integer value) {
            addCriterion("turn_num >=", value, "turnNum");
            return (Criteria) this;
        }

        public Criteria andTurnNumLessThan(Integer value) {
            addCriterion("turn_num <", value, "turnNum");
            return (Criteria) this;
        }

        public Criteria andTurnNumLessThanOrEqualTo(Integer value) {
            addCriterion("turn_num <=", value, "turnNum");
            return (Criteria) this;
        }

        public Criteria andTurnNumIn(List<Integer> values) {
            addCriterion("turn_num in", values, "turnNum");
            return (Criteria) this;
        }

        public Criteria andTurnNumNotIn(List<Integer> values) {
            addCriterion("turn_num not in", values, "turnNum");
            return (Criteria) this;
        }

        public Criteria andTurnNumBetween(Integer value1, Integer value2) {
            addCriterion("turn_num between", value1, value2, "turnNum");
            return (Criteria) this;
        }

        public Criteria andTurnNumNotBetween(Integer value1, Integer value2) {
            addCriterion("turn_num not between", value1, value2, "turnNum");
            return (Criteria) this;
        }

        public Criteria andTurnDescIsNull() {
            addCriterion("turn_desc is null");
            return (Criteria) this;
        }

        public Criteria andTurnDescIsNotNull() {
            addCriterion("turn_desc is not null");
            return (Criteria) this;
        }

        public Criteria andTurnDescEqualTo(String value) {
            addCriterion("turn_desc =", value, "turnDesc");
            return (Criteria) this;
        }

        public Criteria andTurnDescNotEqualTo(String value) {
            addCriterion("turn_desc <>", value, "turnDesc");
            return (Criteria) this;
        }

        public Criteria andTurnDescGreaterThan(String value) {
            addCriterion("turn_desc >", value, "turnDesc");
            return (Criteria) this;
        }

        public Criteria andTurnDescGreaterThanOrEqualTo(String value) {
            addCriterion("turn_desc >=", value, "turnDesc");
            return (Criteria) this;
        }

        public Criteria andTurnDescLessThan(String value) {
            addCriterion("turn_desc <", value, "turnDesc");
            return (Criteria) this;
        }

        public Criteria andTurnDescLessThanOrEqualTo(String value) {
            addCriterion("turn_desc <=", value, "turnDesc");
            return (Criteria) this;
        }

        public Criteria andTurnDescLike(String value) {
            addCriterion("turn_desc like", value, "turnDesc");
            return (Criteria) this;
        }

        public Criteria andTurnDescNotLike(String value) {
            addCriterion("turn_desc not like", value, "turnDesc");
            return (Criteria) this;
        }

        public Criteria andTurnDescIn(List<String> values) {
            addCriterion("turn_desc in", values, "turnDesc");
            return (Criteria) this;
        }

        public Criteria andTurnDescNotIn(List<String> values) {
            addCriterion("turn_desc not in", values, "turnDesc");
            return (Criteria) this;
        }

        public Criteria andTurnDescBetween(String value1, String value2) {
            addCriterion("turn_desc between", value1, value2, "turnDesc");
            return (Criteria) this;
        }

        public Criteria andTurnDescNotBetween(String value1, String value2) {
            addCriterion("turn_desc not between", value1, value2, "turnDesc");
            return (Criteria) this;
        }

        public Criteria andStartVideoIdIsNull() {
            addCriterion("start_video_id is null");
            return (Criteria) this;
        }

        public Criteria andStartVideoIdIsNotNull() {
            addCriterion("start_video_id is not null");
            return (Criteria) this;
        }

        public Criteria andStartVideoIdEqualTo(Integer value) {
            addCriterion("start_video_id =", value, "startVideoId");
            return (Criteria) this;
        }

        public Criteria andStartVideoIdNotEqualTo(Integer value) {
            addCriterion("start_video_id <>", value, "startVideoId");
            return (Criteria) this;
        }

        public Criteria andStartVideoIdGreaterThan(Integer value) {
            addCriterion("start_video_id >", value, "startVideoId");
            return (Criteria) this;
        }

        public Criteria andStartVideoIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("start_video_id >=", value, "startVideoId");
            return (Criteria) this;
        }

        public Criteria andStartVideoIdLessThan(Integer value) {
            addCriterion("start_video_id <", value, "startVideoId");
            return (Criteria) this;
        }

        public Criteria andStartVideoIdLessThanOrEqualTo(Integer value) {
            addCriterion("start_video_id <=", value, "startVideoId");
            return (Criteria) this;
        }

        public Criteria andStartVideoIdIn(List<Integer> values) {
            addCriterion("start_video_id in", values, "startVideoId");
            return (Criteria) this;
        }

        public Criteria andStartVideoIdNotIn(List<Integer> values) {
            addCriterion("start_video_id not in", values, "startVideoId");
            return (Criteria) this;
        }

        public Criteria andStartVideoIdBetween(Integer value1, Integer value2) {
            addCriterion("start_video_id between", value1, value2, "startVideoId");
            return (Criteria) this;
        }

        public Criteria andStartVideoIdNotBetween(Integer value1, Integer value2) {
            addCriterion("start_video_id not between", value1, value2, "startVideoId");
            return (Criteria) this;
        }

        public Criteria andEndVideoIdIsNull() {
            addCriterion("end_video_id is null");
            return (Criteria) this;
        }

        public Criteria andEndVideoIdIsNotNull() {
            addCriterion("end_video_id is not null");
            return (Criteria) this;
        }

        public Criteria andEndVideoIdEqualTo(Integer value) {
            addCriterion("end_video_id =", value, "endVideoId");
            return (Criteria) this;
        }

        public Criteria andEndVideoIdNotEqualTo(Integer value) {
            addCriterion("end_video_id <>", value, "endVideoId");
            return (Criteria) this;
        }

        public Criteria andEndVideoIdGreaterThan(Integer value) {
            addCriterion("end_video_id >", value, "endVideoId");
            return (Criteria) this;
        }

        public Criteria andEndVideoIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("end_video_id >=", value, "endVideoId");
            return (Criteria) this;
        }

        public Criteria andEndVideoIdLessThan(Integer value) {
            addCriterion("end_video_id <", value, "endVideoId");
            return (Criteria) this;
        }

        public Criteria andEndVideoIdLessThanOrEqualTo(Integer value) {
            addCriterion("end_video_id <=", value, "endVideoId");
            return (Criteria) this;
        }

        public Criteria andEndVideoIdIn(List<Integer> values) {
            addCriterion("end_video_id in", values, "endVideoId");
            return (Criteria) this;
        }

        public Criteria andEndVideoIdNotIn(List<Integer> values) {
            addCriterion("end_video_id not in", values, "endVideoId");
            return (Criteria) this;
        }

        public Criteria andEndVideoIdBetween(Integer value1, Integer value2) {
            addCriterion("end_video_id between", value1, value2, "endVideoId");
            return (Criteria) this;
        }

        public Criteria andEndVideoIdNotBetween(Integer value1, Integer value2) {
            addCriterion("end_video_id not between", value1, value2, "endVideoId");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNull() {
            addCriterion("update_time is null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNotNull() {
            addCriterion("update_time is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeEqualTo(Date value) {
            addCriterion("update_time =", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotEqualTo(Date value) {
            addCriterion("update_time <>", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThan(Date value) {
            addCriterion("update_time >", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("update_time >=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThan(Date value) {
            addCriterion("update_time <", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThanOrEqualTo(Date value) {
            addCriterion("update_time <=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIn(List<Date> values) {
            addCriterion("update_time in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotIn(List<Date> values) {
            addCriterion("update_time not in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeBetween(Date value1, Date value2) {
            addCriterion("update_time between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotBetween(Date value1, Date value2) {
            addCriterion("update_time not between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("create_time is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("create_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("create_time =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("create_time <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("create_time >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("create_time >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("create_time <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("create_time <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("create_time in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("create_time not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("create_time between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("create_time not between", value1, value2, "createTime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table robot_video_config
     *
     * @mbg.generated do_not_delete_during_merge Fri Aug 24 11:36:26 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table robot_video_config
     *
     * @mbg.generated Fri Aug 24 11:36:26 CST 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}