package com.artqiyi.tanqiu.game.domain;

import java.util.Date;

public class RobotVideoScoreConfig {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column robot_video_score_config.id
     *
     * @mbg.generated Fri Aug 24 11:36:26 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column robot_video_score_config.video_desc
     *
     * @mbg.generated Fri Aug 24 11:36:26 CST 2018
     */
    private String videoDesc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column robot_video_score_config.video_total_score
     *
     * @mbg.generated Fri Aug 24 11:36:26 CST 2018
     */
    private Integer videoTotalScore;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column robot_video_score_config.score_config
     *
     * @mbg.generated Fri Aug 24 11:36:26 CST 2018
     */
    private String scoreConfig;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column robot_video_score_config.update_time
     *
     * @mbg.generated Fri Aug 24 11:36:26 CST 2018
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column robot_video_score_config.create_time
     *
     * @mbg.generated Fri Aug 24 11:36:26 CST 2018
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column robot_video_score_config.id
     *
     * @return the value of robot_video_score_config.id
     *
     * @mbg.generated Fri Aug 24 11:36:26 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column robot_video_score_config.id
     *
     * @param id the value for robot_video_score_config.id
     *
     * @mbg.generated Fri Aug 24 11:36:26 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column robot_video_score_config.video_desc
     *
     * @return the value of robot_video_score_config.video_desc
     *
     * @mbg.generated Fri Aug 24 11:36:26 CST 2018
     */
    public String getVideoDesc() {
        return videoDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column robot_video_score_config.video_desc
     *
     * @param videoDesc the value for robot_video_score_config.video_desc
     *
     * @mbg.generated Fri Aug 24 11:36:26 CST 2018
     */
    public void setVideoDesc(String videoDesc) {
        this.videoDesc = videoDesc == null ? null : videoDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column robot_video_score_config.video_total_score
     *
     * @return the value of robot_video_score_config.video_total_score
     *
     * @mbg.generated Fri Aug 24 11:36:26 CST 2018
     */
    public Integer getVideoTotalScore() {
        return videoTotalScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column robot_video_score_config.video_total_score
     *
     * @param videoTotalScore the value for robot_video_score_config.video_total_score
     *
     * @mbg.generated Fri Aug 24 11:36:26 CST 2018
     */
    public void setVideoTotalScore(Integer videoTotalScore) {
        this.videoTotalScore = videoTotalScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column robot_video_score_config.score_config
     *
     * @return the value of robot_video_score_config.score_config
     *
     * @mbg.generated Fri Aug 24 11:36:26 CST 2018
     */
    public String getScoreConfig() {
        return scoreConfig;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column robot_video_score_config.score_config
     *
     * @param scoreConfig the value for robot_video_score_config.score_config
     *
     * @mbg.generated Fri Aug 24 11:36:26 CST 2018
     */
    public void setScoreConfig(String scoreConfig) {
        this.scoreConfig = scoreConfig == null ? null : scoreConfig.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column robot_video_score_config.update_time
     *
     * @return the value of robot_video_score_config.update_time
     *
     * @mbg.generated Fri Aug 24 11:36:26 CST 2018
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column robot_video_score_config.update_time
     *
     * @param updateTime the value for robot_video_score_config.update_time
     *
     * @mbg.generated Fri Aug 24 11:36:26 CST 2018
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column robot_video_score_config.create_time
     *
     * @return the value of robot_video_score_config.create_time
     *
     * @mbg.generated Fri Aug 24 11:36:26 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column robot_video_score_config.create_time
     *
     * @param createTime the value for robot_video_score_config.create_time
     *
     * @mbg.generated Fri Aug 24 11:36:26 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}