package com.artqiyi.tanqiu.game.domain;

import java.util.Date;

public class RobotVideoConfig {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column robot_video_config.id
     *
     * @mbg.generated Fri Aug 24 11:36:26 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column robot_video_config.game_model_id
     *
     * @mbg.generated Fri Aug 24 11:36:26 CST 2018
     */
    private Long gameModelId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column robot_video_config.game_model_key
     *
     * @mbg.generated Fri Aug 24 11:36:26 CST 2018
     */
    private String gameModelKey;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column robot_video_config.turn_num
     *
     * @mbg.generated Fri Aug 24 11:36:26 CST 2018
     */
    private Integer turnNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column robot_video_config.turn_desc
     *
     * @mbg.generated Fri Aug 24 11:36:26 CST 2018
     */
    private String turnDesc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column robot_video_config.start_video_id
     *
     * @mbg.generated Fri Aug 24 11:36:26 CST 2018
     */
    private Integer startVideoId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column robot_video_config.end_video_id
     *
     * @mbg.generated Fri Aug 24 11:36:26 CST 2018
     */
    private Integer endVideoId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column robot_video_config.update_time
     *
     * @mbg.generated Fri Aug 24 11:36:26 CST 2018
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column robot_video_config.create_time
     *
     * @mbg.generated Fri Aug 24 11:36:26 CST 2018
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column robot_video_config.id
     *
     * @return the value of robot_video_config.id
     *
     * @mbg.generated Fri Aug 24 11:36:26 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column robot_video_config.id
     *
     * @param id the value for robot_video_config.id
     *
     * @mbg.generated Fri Aug 24 11:36:26 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column robot_video_config.game_model_id
     *
     * @return the value of robot_video_config.game_model_id
     *
     * @mbg.generated Fri Aug 24 11:36:26 CST 2018
     */
    public Long getGameModelId() {
        return gameModelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column robot_video_config.game_model_id
     *
     * @param gameModelId the value for robot_video_config.game_model_id
     *
     * @mbg.generated Fri Aug 24 11:36:26 CST 2018
     */
    public void setGameModelId(Long gameModelId) {
        this.gameModelId = gameModelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column robot_video_config.game_model_key
     *
     * @return the value of robot_video_config.game_model_key
     *
     * @mbg.generated Fri Aug 24 11:36:26 CST 2018
     */
    public String getGameModelKey() {
        return gameModelKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column robot_video_config.game_model_key
     *
     * @param gameModelKey the value for robot_video_config.game_model_key
     *
     * @mbg.generated Fri Aug 24 11:36:26 CST 2018
     */
    public void setGameModelKey(String gameModelKey) {
        this.gameModelKey = gameModelKey == null ? null : gameModelKey.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column robot_video_config.turn_num
     *
     * @return the value of robot_video_config.turn_num
     *
     * @mbg.generated Fri Aug 24 11:36:26 CST 2018
     */
    public Integer getTurnNum() {
        return turnNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column robot_video_config.turn_num
     *
     * @param turnNum the value for robot_video_config.turn_num
     *
     * @mbg.generated Fri Aug 24 11:36:26 CST 2018
     */
    public void setTurnNum(Integer turnNum) {
        this.turnNum = turnNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column robot_video_config.turn_desc
     *
     * @return the value of robot_video_config.turn_desc
     *
     * @mbg.generated Fri Aug 24 11:36:26 CST 2018
     */
    public String getTurnDesc() {
        return turnDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column robot_video_config.turn_desc
     *
     * @param turnDesc the value for robot_video_config.turn_desc
     *
     * @mbg.generated Fri Aug 24 11:36:26 CST 2018
     */
    public void setTurnDesc(String turnDesc) {
        this.turnDesc = turnDesc == null ? null : turnDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column robot_video_config.start_video_id
     *
     * @return the value of robot_video_config.start_video_id
     *
     * @mbg.generated Fri Aug 24 11:36:26 CST 2018
     */
    public Integer getStartVideoId() {
        return startVideoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column robot_video_config.start_video_id
     *
     * @param startVideoId the value for robot_video_config.start_video_id
     *
     * @mbg.generated Fri Aug 24 11:36:26 CST 2018
     */
    public void setStartVideoId(Integer startVideoId) {
        this.startVideoId = startVideoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column robot_video_config.end_video_id
     *
     * @return the value of robot_video_config.end_video_id
     *
     * @mbg.generated Fri Aug 24 11:36:26 CST 2018
     */
    public Integer getEndVideoId() {
        return endVideoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column robot_video_config.end_video_id
     *
     * @param endVideoId the value for robot_video_config.end_video_id
     *
     * @mbg.generated Fri Aug 24 11:36:26 CST 2018
     */
    public void setEndVideoId(Integer endVideoId) {
        this.endVideoId = endVideoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column robot_video_config.update_time
     *
     * @return the value of robot_video_config.update_time
     *
     * @mbg.generated Fri Aug 24 11:36:26 CST 2018
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column robot_video_config.update_time
     *
     * @param updateTime the value for robot_video_config.update_time
     *
     * @mbg.generated Fri Aug 24 11:36:26 CST 2018
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column robot_video_config.create_time
     *
     * @return the value of robot_video_config.create_time
     *
     * @mbg.generated Fri Aug 24 11:36:26 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column robot_video_config.create_time
     *
     * @param createTime the value for robot_video_config.create_time
     *
     * @mbg.generated Fri Aug 24 11:36:26 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}