package com.artqiyi.tanqiu.system.domain;

import java.util.Date;

public class SystemDistribution {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_distribution.distr_id
     *
     * @mbg.generated Wed Jul 25 19:46:27 CST 2018
     */
    private Integer distrId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_distribution.app_type
     *
     * @mbg.generated Wed Jul 25 19:46:27 CST 2018
     */
    private Short appType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_distribution.version
     *
     * @mbg.generated Wed Jul 25 19:46:27 CST 2018
     */
    private String version;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_distribution.app_store_id
     *
     * @mbg.generated Wed Jul 25 19:46:27 CST 2018
     */
    private Short appStoreId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_distribution.distr_state
     *
     * @mbg.generated Wed Jul 25 19:46:27 CST 2018
     */
    private Short distrState;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_distribution.create_time
     *
     * @mbg.generated Wed Jul 25 19:46:27 CST 2018
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_distribution.update_time
     *
     * @mbg.generated Wed Jul 25 19:46:27 CST 2018
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_distribution.distr_id
     *
     * @return the value of system_distribution.distr_id
     *
     * @mbg.generated Wed Jul 25 19:46:27 CST 2018
     */
    public Integer getDistrId() {
        return distrId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_distribution.distr_id
     *
     * @param distrId the value for system_distribution.distr_id
     *
     * @mbg.generated Wed Jul 25 19:46:27 CST 2018
     */
    public void setDistrId(Integer distrId) {
        this.distrId = distrId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_distribution.app_type
     *
     * @return the value of system_distribution.app_type
     *
     * @mbg.generated Wed Jul 25 19:46:27 CST 2018
     */
    public Short getAppType() {
        return appType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_distribution.app_type
     *
     * @param appType the value for system_distribution.app_type
     *
     * @mbg.generated Wed Jul 25 19:46:27 CST 2018
     */
    public void setAppType(Short appType) {
        this.appType = appType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_distribution.version
     *
     * @return the value of system_distribution.version
     *
     * @mbg.generated Wed Jul 25 19:46:27 CST 2018
     */
    public String getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_distribution.version
     *
     * @param version the value for system_distribution.version
     *
     * @mbg.generated Wed Jul 25 19:46:27 CST 2018
     */
    public void setVersion(String version) {
        this.version = version == null ? null : version.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_distribution.app_store_id
     *
     * @return the value of system_distribution.app_store_id
     *
     * @mbg.generated Wed Jul 25 19:46:27 CST 2018
     */
    public Short getAppStoreId() {
        return appStoreId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_distribution.app_store_id
     *
     * @param appStoreId the value for system_distribution.app_store_id
     *
     * @mbg.generated Wed Jul 25 19:46:27 CST 2018
     */
    public void setAppStoreId(Short appStoreId) {
        this.appStoreId = appStoreId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_distribution.distr_state
     *
     * @return the value of system_distribution.distr_state
     *
     * @mbg.generated Wed Jul 25 19:46:27 CST 2018
     */
    public Short getDistrState() {
        return distrState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_distribution.distr_state
     *
     * @param distrState the value for system_distribution.distr_state
     *
     * @mbg.generated Wed Jul 25 19:46:27 CST 2018
     */
    public void setDistrState(Short distrState) {
        this.distrState = distrState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_distribution.create_time
     *
     * @return the value of system_distribution.create_time
     *
     * @mbg.generated Wed Jul 25 19:46:27 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_distribution.create_time
     *
     * @param createTime the value for system_distribution.create_time
     *
     * @mbg.generated Wed Jul 25 19:46:27 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_distribution.update_time
     *
     * @return the value of system_distribution.update_time
     *
     * @mbg.generated Wed Jul 25 19:46:27 CST 2018
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_distribution.update_time
     *
     * @param updateTime the value for system_distribution.update_time
     *
     * @mbg.generated Wed Jul 25 19:46:27 CST 2018
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}