package com.artqiyi.tanqiu.job.mapper;

import org.apache.ibatis.annotations.Param;

import com.artqiyi.tanqiu.job.domain.ScheduleJobFailLog;
import com.artqiyi.tanqiu.job.domain.ScheduleJobFailLogExample;

import java.util.List;

public interface ScheduleJobFailLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table schedule_job_fail_log
     *
     * @mbg.generated Fri May 18 14:47:03 CST 2018
     */
    long countByExample(ScheduleJobFailLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table schedule_job_fail_log
     *
     * @mbg.generated Fri May 18 14:47:03 CST 2018
     */
    int deleteByExample(ScheduleJobFailLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table schedule_job_fail_log
     *
     * @mbg.generated Fri May 18 14:47:03 CST 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table schedule_job_fail_log
     *
     * @mbg.generated Fri May 18 14:47:03 CST 2018
     */
    int insert(ScheduleJobFailLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table schedule_job_fail_log
     *
     * @mbg.generated Fri May 18 14:47:03 CST 2018
     */
    int insertSelective(ScheduleJobFailLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table schedule_job_fail_log
     *
     * @mbg.generated Fri May 18 14:47:03 CST 2018
     */
    List<ScheduleJobFailLog> selectByExampleWithBLOBs(ScheduleJobFailLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table schedule_job_fail_log
     *
     * @mbg.generated Fri May 18 14:47:03 CST 2018
     */
    List<ScheduleJobFailLog> selectByExample(ScheduleJobFailLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table schedule_job_fail_log
     *
     * @mbg.generated Fri May 18 14:47:03 CST 2018
     */
    ScheduleJobFailLog selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table schedule_job_fail_log
     *
     * @mbg.generated Fri May 18 14:47:03 CST 2018
     */
    int updateByExampleSelective(@Param("record") ScheduleJobFailLog record, @Param("example") ScheduleJobFailLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table schedule_job_fail_log
     *
     * @mbg.generated Fri May 18 14:47:03 CST 2018
     */
    int updateByExampleWithBLOBs(@Param("record") ScheduleJobFailLog record, @Param("example") ScheduleJobFailLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table schedule_job_fail_log
     *
     * @mbg.generated Fri May 18 14:47:03 CST 2018
     */
    int updateByExample(@Param("record") ScheduleJobFailLog record, @Param("example") ScheduleJobFailLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table schedule_job_fail_log
     *
     * @mbg.generated Fri May 18 14:47:03 CST 2018
     */
    int updateByPrimaryKeySelective(ScheduleJobFailLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table schedule_job_fail_log
     *
     * @mbg.generated Fri May 18 14:47:03 CST 2018
     */
    int updateByPrimaryKeyWithBLOBs(ScheduleJobFailLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table schedule_job_fail_log
     *
     * @mbg.generated Fri May 18 14:47:03 CST 2018
     */
    int updateByPrimaryKey(ScheduleJobFailLog record);
}