package com.artqiyi.tanqiu.system.mapper;

import com.artqiyi.tanqiu.system.domain.SystemDistribution;
import com.artqiyi.tanqiu.system.domain.SystemDistributionExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SystemDistributionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_distribution
     *
     * @mbg.generated Wed Jul 25 19:46:27 CST 2018
     */
    long countByExample(SystemDistributionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_distribution
     *
     * @mbg.generated Wed Jul 25 19:46:27 CST 2018
     */
    int deleteByExample(SystemDistributionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_distribution
     *
     * @mbg.generated Wed Jul 25 19:46:27 CST 2018
     */
    int deleteByPrimaryKey(Integer distrId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_distribution
     *
     * @mbg.generated Wed Jul 25 19:46:27 CST 2018
     */
    int insert(SystemDistribution entity);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_distribution
     *
     * @mbg.generated Wed Jul 25 19:46:27 CST 2018
     */
    int insertSelective(SystemDistribution entity);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_distribution
     *
     * @mbg.generated Wed Jul 25 19:46:27 CST 2018
     */
    List<SystemDistribution> selectByExample(SystemDistributionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_distribution
     *
     * @mbg.generated Wed Jul 25 19:46:27 CST 2018
     */
    SystemDistribution selectByPrimaryKey(Integer distrId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_distribution
     *
     * @mbg.generated Wed Jul 25 19:46:27 CST 2018
     */
    int updateByExampleSelective(@Param("record") SystemDistribution record, @Param("example") SystemDistributionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_distribution
     *
     * @mbg.generated Wed Jul 25 19:46:27 CST 2018
     */
    int updateByExample(@Param("record") SystemDistribution record, @Param("example") SystemDistributionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_distribution
     *
     * @mbg.generated Wed Jul 25 19:46:27 CST 2018
     */
    int updateByPrimaryKeySelective(SystemDistribution entity);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_distribution
     *
     * @mbg.generated Wed Jul 25 19:46:27 CST 2018
     */
    int updateByPrimaryKey(SystemDistribution entity);
}