package com.artqiyi.tanqiu.game.mapper;

import com.artqiyi.tanqiu.game.domain.GameModel;
import com.artqiyi.tanqiu.game.domain.GameModelExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface GameModelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_model
     *
     * @mbg.generated Tue Jul 03 17:01:57 CST 2018
     */
    long countByExample(GameModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_model
     *
     * @mbg.generated Tue Jul 03 17:01:57 CST 2018
     */
    int deleteByExample(GameModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_model
     *
     * @mbg.generated Tue Jul 03 17:01:57 CST 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_model
     *
     * @mbg.generated Tue Jul 03 17:01:57 CST 2018
     */
    int insert(GameModel entity);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_model
     *
     * @mbg.generated Tue Jul 03 17:01:57 CST 2018
     */
    int insertSelective(GameModel entity);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_model
     *
     * @mbg.generated Tue Jul 03 17:01:57 CST 2018
     */
    List<GameModel> selectByExample(GameModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_model
     *
     * @mbg.generated Tue Jul 03 17:01:57 CST 2018
     */
    GameModel selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_model
     *
     * @mbg.generated Tue Jul 03 17:01:57 CST 2018
     */
    int updateByExampleSelective(@Param("record") GameModel record, @Param("example") GameModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_model
     *
     * @mbg.generated Tue Jul 03 17:01:57 CST 2018
     */
    int updateByExample(@Param("record") GameModel record, @Param("example") GameModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_model
     *
     * @mbg.generated Tue Jul 03 17:01:57 CST 2018
     */
    int updateByPrimaryKeySelective(GameModel entity);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_model
     *
     * @mbg.generated Tue Jul 03 17:01:57 CST 2018
     */
    int updateByPrimaryKey(GameModel entity);
}