package com.artqiyi.tanqiu.game.mapper;

import com.artqiyi.tanqiu.game.domain.GameRedpacketUserRecords;
import com.artqiyi.tanqiu.game.domain.GameRedpacketUserRecordsExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface GameRedpacketUserRecordsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_redpacket_user_records
     *
     * @mbg.generated Tue Jul 24 18:34:57 CST 2018
     */
    long countByExample(GameRedpacketUserRecordsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_redpacket_user_records
     *
     * @mbg.generated Tue Jul 24 18:34:57 CST 2018
     */
    int deleteByExample(GameRedpacketUserRecordsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_redpacket_user_records
     *
     * @mbg.generated Tue Jul 24 18:34:57 CST 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_redpacket_user_records
     *
     * @mbg.generated Tue Jul 24 18:34:57 CST 2018
     */
    int insert(GameRedpacketUserRecords entity);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_redpacket_user_records
     *
     * @mbg.generated Tue Jul 24 18:34:57 CST 2018
     */
    int insertSelective(GameRedpacketUserRecords entity);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_redpacket_user_records
     *
     * @mbg.generated Tue Jul 24 18:34:57 CST 2018
     */
    List<GameRedpacketUserRecords> selectByExample(GameRedpacketUserRecordsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_redpacket_user_records
     *
     * @mbg.generated Tue Jul 24 18:34:57 CST 2018
     */
    GameRedpacketUserRecords selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_redpacket_user_records
     *
     * @mbg.generated Tue Jul 24 18:34:57 CST 2018
     */
    int updateByExampleSelective(@Param("record") GameRedpacketUserRecords record, @Param("example") GameRedpacketUserRecordsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_redpacket_user_records
     *
     * @mbg.generated Tue Jul 24 18:34:57 CST 2018
     */
    int updateByExample(@Param("record") GameRedpacketUserRecords record, @Param("example") GameRedpacketUserRecordsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_redpacket_user_records
     *
     * @mbg.generated Tue Jul 24 18:34:57 CST 2018
     */
    int updateByPrimaryKeySelective(GameRedpacketUserRecords entity);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_redpacket_user_records
     *
     * @mbg.generated Tue Jul 24 18:34:57 CST 2018
     */
    int updateByPrimaryKey(GameRedpacketUserRecords entity);
}