package com.artqiyi.tanqiu.game.mapper;

import com.artqiyi.tanqiu.game.domain.GameRankRecord;
import com.artqiyi.tanqiu.game.domain.GameRankRecordExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface GameRankRecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_rank_record
     *
     * @mbg.generated Tue Jul 03 17:01:57 CST 2018
     */
    long countByExample(GameRankRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_rank_record
     *
     * @mbg.generated Tue Jul 03 17:01:57 CST 2018
     */
    int deleteByExample(GameRankRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_rank_record
     *
     * @mbg.generated Tue Jul 03 17:01:57 CST 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_rank_record
     *
     * @mbg.generated Tue Jul 03 17:01:57 CST 2018
     */
    int insert(GameRankRecord entity);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_rank_record
     *
     * @mbg.generated Tue Jul 03 17:01:57 CST 2018
     */
    int insertSelective(GameRankRecord entity);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_rank_record
     *
     * @mbg.generated Tue Jul 03 17:01:57 CST 2018
     */
    List<GameRankRecord> selectByExample(GameRankRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_rank_record
     *
     * @mbg.generated Tue Jul 03 17:01:57 CST 2018
     */
    GameRankRecord selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_rank_record
     *
     * @mbg.generated Tue Jul 03 17:01:57 CST 2018
     */
    int updateByExampleSelective(@Param("record") GameRankRecord record, @Param("example") GameRankRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_rank_record
     *
     * @mbg.generated Tue Jul 03 17:01:57 CST 2018
     */
    int updateByExample(@Param("record") GameRankRecord record, @Param("example") GameRankRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_rank_record
     *
     * @mbg.generated Tue Jul 03 17:01:57 CST 2018
     */
    int updateByPrimaryKeySelective(GameRankRecord entity);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_rank_record
     *
     * @mbg.generated Tue Jul 03 17:01:57 CST 2018
     */
    int updateByPrimaryKey(GameRankRecord entity);
}