package com.artqiyi.tanqiu.game.mapper;

import com.artqiyi.tanqiu.game.domain.GameDifficultyConfig;
import com.artqiyi.tanqiu.game.domain.GameDifficultyConfigExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface GameDifficultyConfigMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_difficulty_config
     *
     * @mbg.generated Mon Jul 23 18:10:11 CST 2018
     */
    long countByExample(GameDifficultyConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_difficulty_config
     *
     * @mbg.generated Mon Jul 23 18:10:11 CST 2018
     */
    int deleteByExample(GameDifficultyConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_difficulty_config
     *
     * @mbg.generated Mon Jul 23 18:10:11 CST 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_difficulty_config
     *
     * @mbg.generated Mon Jul 23 18:10:11 CST 2018
     */
    int insert(GameDifficultyConfig entity);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_difficulty_config
     *
     * @mbg.generated Mon Jul 23 18:10:11 CST 2018
     */
    int insertSelective(GameDifficultyConfig entity);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_difficulty_config
     *
     * @mbg.generated Mon Jul 23 18:10:11 CST 2018
     */
    List<GameDifficultyConfig> selectByExample(GameDifficultyConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_difficulty_config
     *
     * @mbg.generated Mon Jul 23 18:10:11 CST 2018
     */
    GameDifficultyConfig selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_difficulty_config
     *
     * @mbg.generated Mon Jul 23 18:10:11 CST 2018
     */
    int updateByExampleSelective(@Param("record") GameDifficultyConfig record, @Param("example") GameDifficultyConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_difficulty_config
     *
     * @mbg.generated Mon Jul 23 18:10:11 CST 2018
     */
    int updateByExample(@Param("record") GameDifficultyConfig record, @Param("example") GameDifficultyConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_difficulty_config
     *
     * @mbg.generated Mon Jul 23 18:10:11 CST 2018
     */
    int updateByPrimaryKeySelective(GameDifficultyConfig entity);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_difficulty_config
     *
     * @mbg.generated Mon Jul 23 18:10:11 CST 2018
     */
    int updateByPrimaryKey(GameDifficultyConfig entity);
}