package com.artqiyi.tanqiu.game.mapper;

import com.artqiyi.tanqiu.game.domain.GameRedpacketRecords;
import com.artqiyi.tanqiu.game.domain.GameRedpacketRecordsExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface GameRedpacketRecordsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_redpacket_records
     *
     * @mbg.generated Mon Jul 23 18:10:11 CST 2018
     */
    long countByExample(GameRedpacketRecordsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_redpacket_records
     *
     * @mbg.generated Mon Jul 23 18:10:11 CST 2018
     */
    int deleteByExample(GameRedpacketRecordsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_redpacket_records
     *
     * @mbg.generated Mon Jul 23 18:10:11 CST 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_redpacket_records
     *
     * @mbg.generated Mon Jul 23 18:10:11 CST 2018
     */
    int insert(GameRedpacketRecords entity);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_redpacket_records
     *
     * @mbg.generated Mon Jul 23 18:10:11 CST 2018
     */
    int insertSelective(GameRedpacketRecords entity);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_redpacket_records
     *
     * @mbg.generated Mon Jul 23 18:10:11 CST 2018
     */
    List<GameRedpacketRecords> selectByExample(GameRedpacketRecordsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_redpacket_records
     *
     * @mbg.generated Mon Jul 23 18:10:11 CST 2018
     */
    GameRedpacketRecords selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_redpacket_records
     *
     * @mbg.generated Mon Jul 23 18:10:11 CST 2018
     */
    int updateByExampleSelective(@Param("record") GameRedpacketRecords record, @Param("example") GameRedpacketRecordsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_redpacket_records
     *
     * @mbg.generated Mon Jul 23 18:10:11 CST 2018
     */
    int updateByExample(@Param("record") GameRedpacketRecords record, @Param("example") GameRedpacketRecordsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_redpacket_records
     *
     * @mbg.generated Mon Jul 23 18:10:11 CST 2018
     */
    int updateByPrimaryKeySelective(GameRedpacketRecords entity);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_redpacket_records
     *
     * @mbg.generated Mon Jul 23 18:10:11 CST 2018
     */
    int updateByPrimaryKey(GameRedpacketRecords entity);
}