package com.artqiyi.tanqiu.game.mapper;

import com.artqiyi.tanqiu.game.domain.GameRedpacketPrizeConfig;
import com.artqiyi.tanqiu.game.domain.GameRedpacketPrizeConfigExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface GameRedpacketPrizeConfigMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_redpacket_prize_config
     *
     * @mbg.generated Mon Jul 23 18:10:11 CST 2018
     */
    long countByExample(GameRedpacketPrizeConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_redpacket_prize_config
     *
     * @mbg.generated Mon Jul 23 18:10:11 CST 2018
     */
    int deleteByExample(GameRedpacketPrizeConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_redpacket_prize_config
     *
     * @mbg.generated Mon Jul 23 18:10:11 CST 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_redpacket_prize_config
     *
     * @mbg.generated Mon Jul 23 18:10:11 CST 2018
     */
    int insert(GameRedpacketPrizeConfig entity);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_redpacket_prize_config
     *
     * @mbg.generated Mon Jul 23 18:10:11 CST 2018
     */
    int insertSelective(GameRedpacketPrizeConfig entity);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_redpacket_prize_config
     *
     * @mbg.generated Mon Jul 23 18:10:11 CST 2018
     */
    List<GameRedpacketPrizeConfig> selectByExample(GameRedpacketPrizeConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_redpacket_prize_config
     *
     * @mbg.generated Mon Jul 23 18:10:11 CST 2018
     */
    GameRedpacketPrizeConfig selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_redpacket_prize_config
     *
     * @mbg.generated Mon Jul 23 18:10:11 CST 2018
     */
    int updateByExampleSelective(@Param("record") GameRedpacketPrizeConfig record, @Param("example") GameRedpacketPrizeConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_redpacket_prize_config
     *
     * @mbg.generated Mon Jul 23 18:10:11 CST 2018
     */
    int updateByExample(@Param("record") GameRedpacketPrizeConfig record, @Param("example") GameRedpacketPrizeConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_redpacket_prize_config
     *
     * @mbg.generated Mon Jul 23 18:10:11 CST 2018
     */
    int updateByPrimaryKeySelective(GameRedpacketPrizeConfig entity);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_redpacket_prize_config
     *
     * @mbg.generated Mon Jul 23 18:10:11 CST 2018
     */
    int updateByPrimaryKey(GameRedpacketPrizeConfig entity);
}