package com.artqiyi.tanqiu.game.mapper;

import com.artqiyi.tanqiu.game.domain.GameRedpacketRewardRecord;
import com.artqiyi.tanqiu.game.domain.GameRedpacketRewardRecordExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface GameRedpacketRewardRecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_redpacket_reward_record
     *
     * @mbg.generated Sat Jul 28 18:17:07 CST 2018
     */
    long countByExample(GameRedpacketRewardRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_redpacket_reward_record
     *
     * @mbg.generated Sat Jul 28 18:17:07 CST 2018
     */
    int deleteByExample(GameRedpacketRewardRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_redpacket_reward_record
     *
     * @mbg.generated Sat Jul 28 18:17:07 CST 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_redpacket_reward_record
     *
     * @mbg.generated Sat Jul 28 18:17:07 CST 2018
     */
    int insert(GameRedpacketRewardRecord entity);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_redpacket_reward_record
     *
     * @mbg.generated Sat Jul 28 18:17:07 CST 2018
     */
    int insertSelective(GameRedpacketRewardRecord entity);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_redpacket_reward_record
     *
     * @mbg.generated Sat Jul 28 18:17:07 CST 2018
     */
    List<GameRedpacketRewardRecord> selectByExample(GameRedpacketRewardRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_redpacket_reward_record
     *
     * @mbg.generated Sat Jul 28 18:17:07 CST 2018
     */
    GameRedpacketRewardRecord selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_redpacket_reward_record
     *
     * @mbg.generated Sat Jul 28 18:17:07 CST 2018
     */
    int updateByExampleSelective(@Param("record") GameRedpacketRewardRecord record, @Param("example") GameRedpacketRewardRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_redpacket_reward_record
     *
     * @mbg.generated Sat Jul 28 18:17:07 CST 2018
     */
    int updateByExample(@Param("record") GameRedpacketRewardRecord record, @Param("example") GameRedpacketRewardRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_redpacket_reward_record
     *
     * @mbg.generated Sat Jul 28 18:17:07 CST 2018
     */
    int updateByPrimaryKeySelective(GameRedpacketRewardRecord entity);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_redpacket_reward_record
     *
     * @mbg.generated Sat Jul 28 18:17:07 CST 2018
     */
    int updateByPrimaryKey(GameRedpacketRewardRecord entity);
}