package com.artqiyi.tanqiu.game.mapper;

import com.artqiyi.tanqiu.game.domain.RobotVideoScoreConfig;
import com.artqiyi.tanqiu.game.domain.RobotVideoScoreConfigExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface RobotVideoScoreConfigMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table robot_video_score_config
     *
     * @mbg.generated Fri Aug 24 11:36:26 CST 2018
     */
    long countByExample(RobotVideoScoreConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table robot_video_score_config
     *
     * @mbg.generated Fri Aug 24 11:36:26 CST 2018
     */
    int deleteByExample(RobotVideoScoreConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table robot_video_score_config
     *
     * @mbg.generated Fri Aug 24 11:36:26 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table robot_video_score_config
     *
     * @mbg.generated Fri Aug 24 11:36:26 CST 2018
     */
    int insert(RobotVideoScoreConfig entity);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table robot_video_score_config
     *
     * @mbg.generated Fri Aug 24 11:36:26 CST 2018
     */
    int insertSelective(RobotVideoScoreConfig entity);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table robot_video_score_config
     *
     * @mbg.generated Fri Aug 24 11:36:26 CST 2018
     */
    List<RobotVideoScoreConfig> selectByExample(RobotVideoScoreConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table robot_video_score_config
     *
     * @mbg.generated Fri Aug 24 11:36:26 CST 2018
     */
    RobotVideoScoreConfig selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table robot_video_score_config
     *
     * @mbg.generated Fri Aug 24 11:36:26 CST 2018
     */
    int updateByExampleSelective(@Param("record") RobotVideoScoreConfig record, @Param("example") RobotVideoScoreConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table robot_video_score_config
     *
     * @mbg.generated Fri Aug 24 11:36:26 CST 2018
     */
    int updateByExample(@Param("record") RobotVideoScoreConfig record, @Param("example") RobotVideoScoreConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table robot_video_score_config
     *
     * @mbg.generated Fri Aug 24 11:36:26 CST 2018
     */
    int updateByPrimaryKeySelective(RobotVideoScoreConfig entity);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table robot_video_score_config
     *
     * @mbg.generated Fri Aug 24 11:36:26 CST 2018
     */
    int updateByPrimaryKey(RobotVideoScoreConfig entity);
}