package com.artqiyi.tanqiu.game.mapper;

import com.artqiyi.tanqiu.game.domain.RobotVideoConfig;
import com.artqiyi.tanqiu.game.domain.RobotVideoConfigExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface RobotVideoConfigMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table robot_video_config
     *
     * @mbg.generated Fri Aug 24 11:36:26 CST 2018
     */
    long countByExample(RobotVideoConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table robot_video_config
     *
     * @mbg.generated Fri Aug 24 11:36:26 CST 2018
     */
    int deleteByExample(RobotVideoConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table robot_video_config
     *
     * @mbg.generated Fri Aug 24 11:36:26 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table robot_video_config
     *
     * @mbg.generated Fri Aug 24 11:36:26 CST 2018
     */
    int insert(RobotVideoConfig entity);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table robot_video_config
     *
     * @mbg.generated Fri Aug 24 11:36:26 CST 2018
     */
    int insertSelective(RobotVideoConfig entity);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table robot_video_config
     *
     * @mbg.generated Fri Aug 24 11:36:26 CST 2018
     */
    List<RobotVideoConfig> selectByExample(RobotVideoConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table robot_video_config
     *
     * @mbg.generated Fri Aug 24 11:36:26 CST 2018
     */
    RobotVideoConfig selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table robot_video_config
     *
     * @mbg.generated Fri Aug 24 11:36:26 CST 2018
     */
    int updateByExampleSelective(@Param("record") RobotVideoConfig record, @Param("example") RobotVideoConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table robot_video_config
     *
     * @mbg.generated Fri Aug 24 11:36:26 CST 2018
     */
    int updateByExample(@Param("record") RobotVideoConfig record, @Param("example") RobotVideoConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table robot_video_config
     *
     * @mbg.generated Fri Aug 24 11:36:26 CST 2018
     */
    int updateByPrimaryKeySelective(RobotVideoConfig entity);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table robot_video_config
     *
     * @mbg.generated Fri Aug 24 11:36:26 CST 2018
     */
    int updateByPrimaryKey(RobotVideoConfig entity);
}